### ISSUE TITLE
I can't upload the video

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/android#1169]
### Steps to reproduce
1. Tap 'Upload', select 'From files'ç
2. Browse to camera folder (<public_storage>/DCIM/Camera/) and select the last video in the list
3. Click in Upload, the application says "Wait a moment" . The dialog never vanishes, and I can't upload the video

IMPORTANT: camera folder has 100s of pictures

Maybe related: after a while, the app crashes, with the next log:

´´´
09-21 13:29:14.515  23946-25245/com.owncloud.android E/art﹕ Throwing OutOfMemoryError "Failed to allocate a 589836 byte allocation with 113524 free bytes and 110KB until OOM"
09-21 13:29:14.555  23946-25245/com.owncloud.android E/ThumbnailsCacheManager﹕ Generation of thumbnail for /storage/emulated/0/DCIM/Camera/IMG_20150823_133829.jpg failed
   java.lang.OutOfMemoryError: Failed to allocate a 589836 byte allocation with 113524 free bytes and 110KB until OOM
           at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
           at android.graphics.Bitmap.nativeCreate(Native Method)
           at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
           at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
           at android.graphics.Bitmap.createBitmap(Bitmap.java:709)
           at android.graphics.Bitmap.createBitmap(Bitmap.java:634)
           at android.media.ThumbnailUtils.transform(ThumbnailUtils.java:436)
           at android.media.ThumbnailUtils.extractThumbnail(ThumbnailUtils.java:226)
           at android.media.ThumbnailUtils.extractThumbnail(ThumbnailUtils.java:201)
           at com.owncloud.android.datamodel.ThumbnailsCacheManager$ThumbnailGenerationTask.addThumbnailToCache(ThumbnailsCacheManager.java:229)
           at com.owncloud.android.datamodel.ThumbnailsCacheManager$ThumbnailGenerationTask.doFileInBackground(ThumbnailsCacheManager.java:351)
           at com.owncloud.android.datamodel.ThumbnailsCacheManager$ThumbnailGenerationTask.doInBackground(ThumbnailsCacheManager.java:182)
           at com.owncloud.android.datamodel.ThumbnailsCacheManager$ThumbnailGenerationTask.doInBackground(ThumbnailsCacheManager.java:143)
           at android.os.AsyncTask$2.call(AsyncTask.java:292)
           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
           at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
´´´

**Comment by davivel** [comment]
Fixed in #1171.

**Comment by Dianafg76** [comment]
I tested this issue, and now is working OK
Closed
