### ISSUE TITLE
Crash of current beta when opening a photo downloaded from the server

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1242]
************ CAUSE OF ERROR ************

	java.lang.NullPointerException
		at com.owncloud.android.ui.fragment.OCFileListFragment$7.onItemCheckedStateChanged(OCFileListFragment.java:348)
		at android.widget.AbsListView$MultiChoiceModeWrapper.onItemCheckedStateChanged(AbsListView.java:6119)
		at android.widget.AbsListView.performItemClick(AbsListView.java:1059)
		at android.widget.AbsListView$PerformClick.run(AbsListView.java:2855)
		at android.widget.AbsListView$1.run(AbsListView.java:3529)
		at android.os.Handler.handleCallback(Handler.java:615)
		at android.os.Handler.dispatchMessage(Handler.java:92)
		at android.os.Looper.loop(Looper.java:137)
		at android.app.ActivityThread.main(ActivityThread.java:4745)
		at java.lang.reflect.Method.invokeNative(Native Method)
		at java.lang.reflect.Method.invoke(Method.java:511)
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
		at dalvik.system.NativeStart.main(Native Method)

************ DEVICE INFORMATION ***********
Brand: rk30sdk
Device: rk30sdk
Model: Woxter Tablet PC 97IPS DUAL
Id: JRO03H
Product: rk30sdk

************ FIRMWARE ************
SDK: 16
Release: 4.1.1
Incremental: eng.lsd.20120924.135651

**Comment by tobiasKaminsky** [comment]
workaround is to manually deselect all items. After that opening a photo is working again.
I will fix this maybe tomorrow.

**Comment by LukeOwncloud** [comment]
Confirmed. Fixed with version 20151109. Closing issue.
