### ISSUE TITLE
Beta: crash when uploading an image

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1255]
***********\* CAUSE OF ERROR ************

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1377)
    at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1395)
    at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:637)
    at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:616)
    at android.support.v4.app.DialogFragment.dismissInternal(DialogFragment.java:201)
    at android.support.v4.app.DialogFragment.dismiss(DialogFragment.java:167)
    at com.owncloud.android.ui.activity.UploadFilesActivity$CheckAvailableSpaceTask.onPostExecute(UploadFilesActivity.java:398)
    at com.owncloud.android.ui.activity.UploadFilesActivity$CheckAvailableSpaceTask.onPostExecute(UploadFilesActivity.java:358)
    at android.os.AsyncTask.finish(AsyncTask.java:651)
    at android.os.AsyncTask.-wrap1(AsyncTask.java)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

***********\* DEVICE INFORMATION ***********
Brand: google
Device: hammerhead
Model: Nexus 5
Id: MRA58K
Product: hammerhead

***********\* FIRMWARE ************
SDK: 23
Release: 6.0
Incremental: 2256973

**Comment by elpraga** [comment]
This happened when the server was busy creating thumbnails, not sure if it is related to the crash though. Nevertheless, the app should not crash even if the server is busy.

**Comment by LukeOwncloud** [comment]
Uploading image works for me with version 20151109. @elpraga please double check!

**Comment by elpraga** [comment]
OK. I'll try to recreate the conditions when at home, I'll make the server busy and then I'll check what happens when I try to upload an image.

**Comment by tobiasKaminsky** [comment]
And please try to reproduce it on the original version.
According to the posted code snippet I cannot see any beta-related code.

**Comment by tobiasKaminsky** [comment]
ping @elpraga :)

**Comment by elpraga** [comment]
Beta 201511121
I did it again! Well, I am not happy about it, but I could investigate more the behaviour. It does not seem to be related to server after all. 

I have two devices - Nexus5 and an older tablet.  On both the legacy app and the beta installed. I tried to open a folder with new photos in the beta app to make the server busy and then tried to upload something both with beta and legacy app.

First when uploading with the beta, it simply said that the server is busy, and the upload did not get through, but without a crash. But I tried to upload with the legacy app and to my suprise it went smoothly eventhough I knew that the server was busy generating the previews.

I ran in problems with both apps when I opened a folder with many photos, triagered the thumbnail generation and then switched to another folder and tried to upload something. - in this case both apps crashed.

Hope this helpes..

************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1377)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1395)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:637)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:616)
	at android.support.v4.app.DialogFragment.dismissInternal(DialogFragment.java:201)
	at android.support.v4.app.DialogFragment.dismiss(DialogFragment.java:167)
	at com.owncloud.android.ui.activity.UploadFilesActivity$CheckAvailableSpaceTask.onPostExecute(UploadFilesActivity.java:399)
	at com.owncloud.android.ui.activity.UploadFilesActivity$CheckAvailableSpaceTask.onPostExecute(UploadFilesActivity.java:359)
	at android.os.AsyncTask.finish(AsyncTask.java:651)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

************ DEVICE INFORMATION ***********
Brand: google
Device: hammerhead
Model: Nexus 5
Id: MRA58N
Product: hammerhead

************ FIRMWARE ************
SDK: 23
Release: 6.0
Incremental: 2289998

**Comment by tobiasKaminsky** [comment]
If this affect both apps, please try both latest versions and confirm if the problem still exists?
