### ISSUE TITLE
Beta: app crashes when copying a file 

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1259]
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
	at com.owncloud.android.ui.activity.FileDisplayActivity.requestCopyOperation(FileDisplayActivity.java:830)
	at com.owncloud.android.ui.activity.FileDisplayActivity.access$300(FileDisplayActivity.java:119)
	at com.owncloud.android.ui.activity.FileDisplayActivity$3.run(FileDisplayActivity.java:694)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

************ DEVICE INFORMATION ***********
Brand: google
Device: hammerhead
Model: Nexus 5
Id: MRA58K
Product: hammerhead

************ FIRMWARE ************
SDK: 23
Release: 6.0
Incremental: 2256973

**Comment by LukeOwncloud** [comment]
Copying file works for me with version 20151109. @elpraga please double check!

**Comment by elpraga** [comment]
I just double checked with Beta 20151113

And it still doesn't work..

```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
	at com.owncloud.android.ui.activity.FileDisplayActivity.requestCopyOperation(FileDisplayActivity.java:834)
	at com.owncloud.android.ui.activity.FileDisplayActivity.access$300(FileDisplayActivity.java:119)
	at com.owncloud.android.ui.activity.FileDisplayActivity$3.run(FileDisplayActivity.java:698)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

************ DEVICE INFORMATION ***********
Brand: google
Device: hammerhead
Model: Nexus 5
Id: MRA58N
Product: hammerhead

************ FIRMWARE ************
SDK: 23
Release: 6.0
Incremental: 2289998
```

**Comment by elpraga** [comment]
I am copying the file from a folder  I share with other people  to a different folder in my OC.

**Comment by tobiasKaminsky** [comment]
Please try the latest beta. You can upgrade from within the app.

**Comment by elpraga** [comment]
Now works in Beta 20151120
