### ISSUE TITLE
Change storage path after upgrading beta

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1298]
Hi @przybylski 
I have updated my beta version (from a very old beta version) and after changing the storage path (by externalSD2) I get:
```
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:304)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.BufferedWriter.close()' on a null object reference
at com.owncloud.android.lib.common.utils.Log_OC.stopLogging(Log_OC.java:108)
at com.owncloud.android.ui.activity.StorageMigrationActivity$FileMigrationTask.doInBackground(StorageMigrationActivity.java:124)
at com.owncloud.android.ui.activity.StorageMigrationActivity$FileMigrationTask.doInBackground(StorageMigrationActivity.java:88)
at android.os.AsyncTask$2.call(AsyncTask.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
```

Can you have a look? :)

**Comment by przybylski** [comment]
Thats interesing, I haven't run into that while testing, I'll have a look, but it looks like its android-library problem :)

**Comment by tobiasKaminsky** [comment]
I have debugged it. 
The first 3 times the mLogPath file exists, but then there is a null file.
Android-library is also your PR, or? 
Maybe I have messed something up when merging your both PRs (or it is a problem with some other PR, that can only occur on beta...?)

**Comment by przybylski** [comment]
The weird thing to me that it appears after 3rd migration, i pushed some fix (in PR) to this but I do need to investigate further.

**Comment by przybylski** [comment]
Ok, this was related with thread racing, it's now fixed in bring_back_logging_arguments branch in android-library

**Comment by tobiasKaminsky** [comment]
Thank you!
I have merged it into beta.
This works now, but I have found a new bug.
