### ISSUE TITLE
[Duplications] [1168] Upload failed

### ISSUE THREAD

**Issue by rperezb** [owncloud/android#1313]
STEPS:
1.- Enable instant upload
2.- Behavior: select: do nothing
3.- Take an image
4.- The image is automatically uploaded

CURRENT BEHAVIOR:
Once the upload finishes, it´s shown a notification of failed upload
However, the file is uploaded

EXPECTED BEHAVIOR:
There is not any notification of failed upload

NOTE: 
This happens too if you select the option: delete
This has not been reproduced if the selected behavior is: copy

LOGS:
````
11-27 09:21:04.372  16868-16899/com.owncloud.android E/FileUploader﹕ Error uploading
    java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
            at java.io.File.fixSlashes(File.java:183)
            at java.io.File.<init>(File.java:130)
            at com.owncloud.android.datamodel.FileDataStorageManager.triggerMediaScan(FileDataStorageManager.java:1562)
            at com.owncloud.android.files.services.FileUploader.saveUploadedFile(FileUploader.java:719)
            at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:575)
            at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:521)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.os.HandlerThread.run(HandlerThread.java:61)
````
Device: Tablet nexus Android 6

**Comment by tobiasKaminsky** [comment]
fixed.
Please try again

**Comment by rperezb** [comment]
working, thx
