### ISSUE TITLE
Storage path: switch to external folder after reinstall

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/android#1330]
Hi @przybylski,

on a fresh install I have switched the storage path to external sdcard and used it a lot.
After a reinstall (due to some tests) I wanted to switch a fresh-install back to the external sdcard.
This does not work as owncloud says that the folder is existing (we talked about it).

Now the question is, how to deal with such a situation? Deleting the folder and download all files once again is not a good option.
The official app does not care if the folder exists and tries to use it, or?
Maybe, if the folder exists the app should ask: "use it" or "rename and move internal folder to external".

What do you think?

**Comment by przybylski** [comment]
I think asking user whether use or overwrite existing folder is better solution. It event match issue filed by @jancborchardt that setting path is overly complicated.

**Comment by tobiasKaminsky** [comment]
You are right, this is the best and (for the user) easiest solution.
If a user does not want to use or overwrite the destination folder he would have rename it manually.

**Comment by marneu** [comment]
Some experience on using the Beta:

Parallel installation on android with ownCloud went ok. After changing to a different location on extSdcard following error occurs (location will not be changed):

```
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to get length of null array
	at com.owncloud.android.ui.activity.StorageMigrationActivity$FileMigrationTask.copyDirs(StorageMigrationActivity.java:218)
	at com.owncloud.android.ui.activity.StorageMigrationActivity$FileMigrationTask.copyFiles(StorageMigrationActivity.java:209)
	at com.owncloud.android.ui.activity.StorageMigrationActivity$FileMigrationTask.doInBackground(StorageMigrationActivity.java:139)
	at com.owncloud.android.ui.activity.StorageMigrationActivity$FileMigrationTask.doInBackground(StorageMigrationActivity.java:88)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

************ DEVICE INFORMATION ***********
Brand: samsung
Device: klte
Model: SM-G900F
Id: LRX21T
Product: kltexx

************ FIRMWARE ************
SDK: 21
Release: 5.0
Incremental: G900FXXU1BOA3
```

I tried to uninstall ownCloud and removed the SDcard folder ownCloud to check to simulate a fresh install. The error remains the same, the newly and empty folder is not moved to the new location.

After trying to reinstall the official app again from store ownCloud installation is refused with error code -505 (stating "ownCloud" can not be installed. Please try again - Trying again leads to the same behavior).

**Comment by marneu** [comment]
Tobias, I'd like to second your thoughts and even go further, the app should check on installation whether it finds an existing data path (based on tag(?)) and use it without notice.

**Comment by przybylski** [comment]
This crash is caused by some changes in "Avoid duplication" in views.
The fix to that is in here: https://github.com/owncloud/android/pull/1302 but I looks like @tobiasKaminsky haven't merged it onto beta

**Comment by przybylski** [comment]
@marneu could you open new bug with crash and assign it to me?

**Comment by marneu** [comment]
ok, I made https://github.com/owncloud/android/issues/1331 but can not assign you nore add a label, sorry.

**Comment by tobiasKaminsky** [comment]
@przybylski what is the status of this issue?

**Comment by przybylski** [comment]
This should work now since some fundamental changes were made

**Comment by tobiasKaminsky** [comment]
Then I close it.
We can reopen it if necessary.

**Comment by marneu** [comment]
Final comment: Works as expected. The original app needs to be uninstalled before installing the beta.
External SDcard is detected and used.
