### ISSUE TITLE
Beta 20151202 crashes on changing to external folder

### ISSUE THREAD

**Issue by marneu** [owncloud/android#1331]
Some experience on using the Beta:

Parallel installation on android with ownCloud went ok. After changing to a different location on extSdcard following error occurs (location will not be changed):

```
java.lang.RuntimeException: An error occured while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:300)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to get length of null array
    at com.owncloud.android.ui.activity.StorageMigrationActivity$FileMigrationTask.copyDirs(StorageMigrationActivity.java:218)
    at com.owncloud.android.ui.activity.StorageMigrationActivity$FileMigrationTask.copyFiles(StorageMigrationActivity.java:209)
    at com.owncloud.android.ui.activity.StorageMigrationActivity$FileMigrationTask.doInBackground(StorageMigrationActivity.java:139)
    at com.owncloud.android.ui.activity.StorageMigrationActivity$FileMigrationTask.doInBackground(StorageMigrationActivity.java:88)
    at android.os.AsyncTask$2.call(AsyncTask.java:288)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    ... 4 more

************ DEVICE INFORMATION ***********
Brand: samsung
Device: klte
Model: SM-G900F
Id: LRX21T
Product: kltexx

************ FIRMWARE ************
SDK: 21
Release: 5.0
Incremental: G900FXXU1BOA3
```

I tried to uninstall ownCloud and removed the SDcard folder ownCloud to check to simulate a fresh install. The error remains the same, the newly and empty folder is not moved to the new location.

After trying to reinstall the official app again from store ownCloud installation is refused with error code -505 (stating "ownCloud" can not be installed. Please try again - Trying again leads to the same behavior).

Addl info: The device is rootet and the SDfix applied.

After removing the beta, the offical app from store can be installed again.

Can I supply further info?

**Comment by tobiasKaminsky** [comment]
@marneu Can you test it with the latest beta?
@przybylski made some changes.

**Comment by marneu** [comment]
The lastest beta 20151226 lacks the functionality using the external sdcard. 
Storage path only shows "Default", which ist selected. Unfortunately it's on the internal sdcard.

Installation of a previous version over the lastest fails, and needs to be uninstalled before going back to the external path enabled 20151222.
The previous version shows "external path" but storage still remains on internal sdcard.
After trying "Costam"(?) a failure occurs, nothing lost, the storge shows "external sdcard", data remains on "internal".
Switching to internal shows "preparing" data remaining in "internal".
Switching back to "external" does nothing, data remain on internal. 
I think there is an option missing (like the linux client) , to select the folder you always want to have in sync (but probably only when on a wlan) without selecting and downloading each separately (where I do not need the ability to sync fotos and movies, just data and docs).
After syncing a folder sometimes a small red sync symbol remains on an object, don't understand why, the object is usable.
Status incomplete.
hth

**Comment by przybylski** [comment]
Whats is your device and android version?

**Comment by przybylski** [comment]
I do not have samsung device, could you please open device shell
`adb shell`
and paste the result of `mount` command?

**Comment by marneu** [comment]
It's an sgs5 -> Android 5.0 (see first entry here)

**Comment by davivel** [comment]
Beta process is going to change. Current beta branch will not be maintained anymore. External storage is not available yet in the stable app, so this issues needs to closed.

Thanks for reporting! :)
