### ISSUE TITLE
[Beta 20151213] App crashes when switching to landscape view

### ISSUE THREAD

**Issue by enoch85** [owncloud/android#1348]
When I rotate the screen when watching videos the app crashes. Tested with files on server, have not tested if they are present locally.

************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.owncloud.android.beta/com.owncloud.android.ui.activity.FileDisplayActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.accounts.Account com.owncloud.android.datamodel.FileDataStorageManager.getAccount()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2354)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2416)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3983)
	at android.app.ActivityThread.access$1000(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1328)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5290)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.accounts.Account com.owncloud.android.datamodel.FileDataStorageManager.getAccount()' on a null object reference
	at com.owncloud.android.ui.preview.PreviewMediaFragment.playVideo(PreviewMediaFragment.java:446)
	at com.owncloud.android.ui.preview.PreviewMediaFragment.onStart(PreviewMediaFragment.java:292)
	at android.support.v4.app.Fragment.performStart(Fragment.java:1986)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1102)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
	at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2047)
	at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:176)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:553)
	at com.owncloud.android.ui.activity.FileActivity.onStart(FileActivity.java:252)
	at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:226)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
	at android.app.Activity.performStart(Activity.java:6104)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
	... 11 more

************ DEVICE INFORMATION ***********
Brand: OnePlus
Device: OnePlus2
Model: ONE A2003
Id: LMY47V
Product: OnePlus2

************ FIRMWARE ************
SDK: 22
Release: 5.1.1
Incremental: 64

**Comment by tobiasKaminsky** [comment]
Please test with latest beta 20151226

**Comment by enoch85** [comment]
Landscape bug fixed!
