### ISSUE TITLE
[Beta 20151213] App crashes when long pressing picture in grid view

### ISSUE THREAD

**Issue by enoch85** [owncloud/android#1350]
***********\* CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.view.ActionMode$Callback.onCreateActionMode(android.view.ActionMode, android.view.Menu)' on a null object reference
    at com.android.internal.policy.impl.PhoneWindow$DecorView$ActionModeCallbackWrapper.onCreateActionMode(PhoneWindow.java:3279)
    at android.support.v7.view.SupportActionModeWrapper$CallbackWrapper.onCreateActionMode(SupportActionModeWrapper.java:155)
    at android.support.v7.app.AppCompatDelegateImplV7$ActionModeCallbackWrapperV7.onCreateActionMode(AppCompatDelegateImplV7.java:1695)
    at android.support.v7.app.WindowDecorActionBar$ActionModeImpl.dispatchOnCreate(WindowDecorActionBar.java:1008)
    at android.support.v7.app.WindowDecorActionBar.startActionMode(WindowDecorActionBar.java:498)
    at android.support.v7.app.AppCompatDelegateImplV7.startSupportActionMode(AppCompatDelegateImplV7.java:645)
    at android.support.v7.app.AppCompatDelegateImplV14$AppCompatWindowCallbackV14.startAsSupportActionMode(AppCompatDelegateImplV14.java:74)
    at android.support.v7.app.AppCompatDelegateImplV14$AppCompatWindowCallbackV14.onWindowStartingActionMode(AppCompatDelegateImplV14.java:58)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.startActionMode(PhoneWindow.java:2699)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.startActionModeForChild(PhoneWindow.java:2686)
    at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
    at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
    at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
    at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
    at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
    at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
    at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
    at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
    at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
    at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
    at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
    at android.view.View.startActionMode(View.java:4887)
    at android.widget.AbsListView.performLongPress(AbsListView.java:3115)
    at android.widget.AbsListView$CheckForLongPress.run(AbsListView.java:3074)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5290)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

***********\* DEVICE INFORMATION ***********
Brand: OnePlus
Device: OnePlus2
Model: ONE A2003
Id: LMY47V
Product: OnePlus2

***********\* FIRMWARE ************
SDK: 22
Release: 5.1.1
Incremental: 64

**Comment by enoch85** [comment]
On the second try it worked.

**Comment by enoch85** [comment]
Related error, when removing picture in grid veiew from server: 

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.Menu.clear()' on a null object reference
	at com.owncloud.android.ui.fragment.OCFileListFragment$7.onItemCheckedStateChanged(OCFileListFragment.java:348)
	at android.widget.AbsListView$MultiChoiceModeWrapper.onItemCheckedStateChanged(AbsListView.java:6230)
	at android.widget.AbsListView.confirmCheckedPositionsById(AbsListView.java:5271)
	at android.widget.AbsListView.handleDataChanged(AbsListView.java:5292)
	at android.widget.GridView.layoutChildren(GridView.java:1208)
	at android.widget.AbsListView.onLayout(AbsListView.java:2151)
	at android.view.View.layout(View.java:15707)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:584)
	at android.view.View.layout(View.java:15707)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15707)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
	at android.view.View.layout(View.java:15707)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15707)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1692)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:15707)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15707)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
	at android.view.View.layout(View.java:15707)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15707)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:435)
	at android.view.View.layout(View.java:15707)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15707)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:15707)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:15707)
	at android.view.ViewGroup.layout(ViewGroup.java:5039)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5891)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5290)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

************ DEVICE INFORMATION ***********
Brand: OnePlus
Device: OnePlus2
Model: ONE A2003
Id: LMY47V
Product: OnePlus2

************ FIRMWARE ************
SDK: 22
Release: 5.1.1
Incremental: 64

**Comment by AndyScherzinger** [comment]
Error still occurs to me with the latest beta branch (long press image in grid view):

java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.view.ActionMode$Callback.onCreateActionMode(android.view.ActionMode, android.view.Menu)' on a null object reference
at com.android.internal.policy.PhoneWindow$DecorView$ActionModeCallback2Wrapper.onCreateActionMode(PhoneWindow.java:3531)
at android.support.v7.view.SupportActionModeWrapper$CallbackWrapper.onCreateActionMode(SupportActionModeWrapper.java:155)
at android.support.v7.app.AppCompatDelegateImplV7$ActionModeCallbackWrapperV7.onCreateActionMode(AppCompatDelegateImplV7.java:1695)
at android.support.v7.app.WindowDecorActionBar$ActionModeImpl.dispatchOnCreate(WindowDecorActionBar.java:1008)
at android.support.v7.app.WindowDecorActionBar.startActionMode(WindowDecorActionBar.java:498)
at android.support.v7.app.AppCompatDelegateImplV7.startSupportActionMode(AppCompatDelegateImplV7.java:645)
at android.support.v7.app.AppCompatDelegateImplV14$AppCompatWindowCallbackV14.startAsSupportActionMode(AppCompatDelegateImplV14.java:74)
at android.support.v7.app.AppCompatDelegateImplV23$AppCompatWindowCallbackV23.onWindowStartingActionMode(AppCompatDelegateImplV23.java:47)
at com.android.internal.policy.PhoneWindow$DecorView.startActionMode(PhoneWindow.java:2748)
at com.android.internal.policy.PhoneWindow$DecorView.startActionModeForChild(PhoneWindow.java:2729)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:812)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:812)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:812)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:812)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:812)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:812)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:812)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:812)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:812)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:812)
at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:812)
at android.view.View.startActionMode(View.java:5341)
at android.view.View.startActionMode(View.java:5325)
at android.widget.AbsListView.performLongPress(AbsListView.java:3142)
at android.widget.AbsListView$CheckForLongPress.run(AbsListView.java:3083)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

************ DEVICE INFORMATION ***********
Brand: google
Device: bullhead
Model: Nexus 5X
Id: MMB29K
Product: bullhead

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: 2419427

**Comment by AndyScherzinger** [comment]
This only happens the first time which is where I think the problem is...

It doesn't happen when I open a folder which is then displayed in grid view, but it happens when I:
* open a folder in list view
* switch to grid view via the top menu
* long press an item

Beware this only happens the very first time in this scenario we a new app start, after that it works until you kill the app process and start over using the above pattern. This might have to do with some initialization missing the first time, don't know.

**Comment by tobiasKaminsky** [comment]
Is this still valid?

**Comment by AndyScherzinger** [comment]
I had this yesterday too, but didn't save the stack trace or anything :(

**Comment by enoch85** [comment]
Lost my phone this weekend to a pickpocket :/ Can't test sorry.

**Comment by davivel** [comment]
> Lost my phone this weekend to a pickpocket :/ Can't test sorry.

Really sad, I'm very sorry :( 

Beta process is going to change. Current beta branch will not be maintained anymore. If this is detected in a stable version, please reopen.

And thanks for reporting! :)
