### ISSUE TITLE
NullpointerException in Beta

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/android#1382]
Installed Beta
Opend Sidebar via Swipe gesture
Closed Sidebar via Swipe gesture
Switched to Grid View
Got this Stacktrace

```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.view.ActionMode$Callback.onCreateActionMode(android.view.ActionMode, android.view.Menu)' on a null object reference
	at com.android.internal.policy.impl.PhoneWindow$DecorView$ActionModeCallbackWrapper.onCreateActionMode(PhoneWindow.java:3539)
	at android.support.v7.view.SupportActionModeWrapper$CallbackWrapper.onCreateActionMode(SupportActionModeWrapper.java:155)
	at android.support.v7.app.AppCompatDelegateImplV7$ActionModeCallbackWrapperV7.onCreateActionMode(AppCompatDelegateImplV7.java:1695)
	at android.support.v7.app.WindowDecorActionBar$ActionModeImpl.dispatchOnCreate(WindowDecorActionBar.java:1008)
	at android.support.v7.app.WindowDecorActionBar.startActionMode(WindowDecorActionBar.java:498)
	at android.support.v7.app.AppCompatDelegateImplV7.startSupportActionMode(AppCompatDelegateImplV7.java:645)
	at android.support.v7.app.AppCompatDelegateImplV14$AppCompatWindowCallbackV14.startAsSupportActionMode(AppCompatDelegateImplV14.java:74)
	at android.support.v7.app.AppCompatDelegateImplV14$AppCompatWindowCallbackV14.onWindowStartingActionMode(AppCompatDelegateImplV14.java:58)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.startActionMode(PhoneWindow.java:2955)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.startActionModeForChild(PhoneWindow.java:2942)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:701)
	at android.view.View.startActionMode(View.java:4890)
	at android.widget.AbsListView.performLongPress(AbsListView.java:3117)
	at android.widget.AbsListView$CheckForLongPress.run(AbsListView.java:3076)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5292)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

************ DEVICE INFORMATION ***********
Brand: google
Device: mako
Model: Nexus 4
Id: LMY48B
Product: occam

************ FIRMWARE ************
SDK: 22
Release: 5.1.1
Incremental: 5cc85cd080
```

**Comment by tobiasKaminsky** [comment]
Cannot reproduce with the latest beta.
Can you retest it please?

**Comment by stefan-niedermann** [comment]
Not reproducable in current beta.
