### ISSUE TITLE
Beta: NPE while trying to change path for instant video upload

### ISSUE THREAD

**Issue by cornzy** [owncloud/android#1405]
* Goto Settings
 * select instant video upload
 * Try to change "upload video path"

************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference
at com.owncloud.android.ui.activity.Preferences$12.onPreferenceClick(Preferences.java:493)
at android.preference.Preference.performClick(Preference.java:1165)
at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:269)
at android.widget.AdapterView.performItemClick(AdapterView.java:339)
at android.widget.AbsListView.performItemClick(AbsListView.java:1544)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3721)
at android.widget.AbsListView$3.run(AbsListView.java:5660)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6837)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

************ DEVICE INFORMATION ***********
Brand: samsung
Device: zerolte
Model: SM-G925F
Id: LMY47X
Product: zeroltexx

************ FIRMWARE ************
SDK: 22
Release: 5.1.1
Incremental: G925FXXS3QOK2

**Comment by AndyScherzinger** [comment]
@cornzy are you running the latest beta release? -> 20160103 ?

**Comment by cornzy** [comment]
Ok,sorry was the previous beta

**Comment by AndyScherzinger** [comment]
OK, no worries, glad to hear it is fixed with the latest version :)
