### ISSUE TITLE
Beta 20160103: Error I got repeatedly when opening a share dialog (server was busy, no clue if relevant)

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1410]
************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1489)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1507)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:613)
	at android.support.v4.app.DialogFragment.dismissInternal(DialogFragment.java:201)
	at android.support.v4.app.DialogFragment.dismiss(DialogFragment.java:167)
	at com.owncloud.android.ui.activity.FileActivity.dismissLoadingDialog(FileActivity.java:885)
	at com.owncloud.android.ui.activity.FileActivity.onRemoteOperationFinish(FileActivity.java:731)
	at com.owncloud.android.ui.activity.ShareActivity.onRemoteOperationFinish(ShareActivity.java:164)
	at com.owncloud.android.utils.GetShareWithUsersAsyncTask.onPostExecute(GetShareWithUsersAsyncTask.java:92)
	at com.owncloud.android.utils.GetShareWithUsersAsyncTask.onPostExecute(GetShareWithUsersAsyncTask.java:44)
	at android.os.AsyncTask.finish(AsyncTask.java:651)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

************ DEVICE INFORMATION ***********
Brand: google
Device: hammerhead
Model: Nexus 5
Id: MMB29K
Product: hammerhead

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: 2419427

**Comment by tobiasKaminsky** [comment]
@elpraga is this still valid?

**Comment by elpraga** [comment]
Cannot reproduce any more on beta 20160313
