### ISSUE TITLE
Beta: Nullpointer on select 

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#1422]
20160109

1 Set list view of some folder. 
2 Exit owncloud app (swipe out) 
3 open owncloud and browse to folder
4 set grid view
5 long click folder

Result:

    ************ CAUSE OF ERROR ************

java.lang.NullPointerException
	at com.android.internal.policy.impl.PhoneWindow$DecorView$ActionModeCallbackWrapper.onCreateActionMode(PhoneWindow.java:2550)
	at android.support.v7.view.SupportActionModeWrapper$CallbackWrapper.onCreateActionMode(SupportActionModeWrapper.java:155)
	at android.support.v7.app.AppCompatDelegateImplV7$ActionModeCallbackWrapperV7.onCreateActionMode(AppCompatDelegateImplV7.java:1695)
	at android.support.v7.app.WindowDecorActionBar$ActionModeImpl.dispatchOnCreate(WindowDecorActionBar.java:1008)
	at android.support.v7.app.WindowDecorActionBar.startActionMode(WindowDecorActionBar.java:498)
	at android.support.v7.app.AppCompatDelegateImplV7.startSupportActionMode(AppCompatDelegateImplV7.java:645)
	at android.support.v7.app.AppCompatDelegateImplV14$AppCompatWindowCallbackV14.startAsSupportActionMode(AppCompatDelegateImplV14.java:74)
	at android.support.v7.app.AppCompatDelegateImplV14$AppCompatWindowCallbackV14.onWindowStartingActionMode(AppCompatDelegateImplV14.java:58)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.startActionMode(PhoneWindow.java:2256)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.startActionModeForChild(PhoneWindow.java:2243)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:623)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:623)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:623)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:623)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:623)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:623)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:623)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:623)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:623)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:623)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:623)
	at android.view.View.startActionMode(View.java:4302)
	at android.widget.AbsListView.performLongPress(AbsListView.java:2805)
	at android.widget.AbsListView$CheckForLongPress.run(AbsListView.java:2765)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5041)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)

************ DEVICE INFORMATION ***********
Brand: google
Device: mako
Model: Nexus 4
Id: JDQ39
Product: occam

************ FIRMWARE ************
SDK: 17
Release: 4.2.2
Incremental: 573038

**Comment by LukeOwncloud** [comment]
Not reproducible anymore.
