### ISSUE TITLE
Beta: Exception on share with owncloud 

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/android#1423]
20160109

1 open any app
2 select share with owncloud 

Result

    ************ CAUSE OF ERROR ************

java.lang.ClassCastException: java.lang.String cannot be cast to com.owncloud.android.datamodel.OCFile
	at com.owncloud.android.ui.activity.ImageSimpleAdapter.getView(ImageSimpleAdapter.java:53)
	at android.widget.AbsListView.obtainView(AbsListView.java:2159)
	at android.widget.ListView.makeAndAddView(ListView.java:1831)
	at android.widget.ListView.fillDown(ListView.java:674)
	at android.widget.ListView.fillFromTop(ListView.java:735)
	at android.widget.ListView.layoutChildren(ListView.java:1652)
	at android.widget.AbsListView.onLayout(AbsListView.java:1994)
	at android.view.View.layout(View.java:14008)
	at android.view.ViewGroup.layout(ViewGroup.java:4373)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14008)
	at android.view.ViewGroup.layout(ViewGroup.java:4373)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1021)
	at android.view.View.layout(View.java:14008)
	at android.view.ViewGroup.layout(ViewGroup.java:4373)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14008)
	at android.view.ViewGroup.layout(ViewGroup.java:4373)
	at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:435)
	at android.view.View.layout(View.java:14008)
	at android.view.ViewGroup.layout(ViewGroup.java:4373)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14008)
	at android.view.ViewGroup.layout(ViewGroup.java:4373)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1663)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1521)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
	at android.view.View.layout(View.java:14008)
	at android.view.ViewGroup.layout(ViewGroup.java:4373)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14008)
	at android.view.ViewGroup.layout(ViewGroup.java:4373)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1892)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1711)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4351)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
	at android.view.Choreographer.doCallbacks(Choreographer.java:562)
	at android.view.Choreographer.doFrame(Choreographer.java:532)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5041)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)

************ DEVICE INFORMATION ***********
Brand: google
Device: mako
Model: Nexus 4
Id: JDQ39
Product: occam

************ FIRMWARE ************
SDK: 17
Release: 4.2.2
Incremental: 573038

**Comment by strugee** [comment]
I can confirm this issue on a Nexus 6P, SDK 23 (CM13/Android 6.0.1), beta 20160109.

**Comment by tobiasKaminsky** [comment]
So I have found the cause: 
https://github.com/owncloud/android/commit/7d5c573766d7b8a5b8113479f29520628e0c7cb0#diff-3e015e85b287e8a0cc4def4d9bf3994d
@masensio IMPORTANT! 
Can you help me here as you have written the code?

https://github.com/owncloud/android/blob/beta/src/com/owncloud/android/ui/activity/Uploader.java#L636
In this line filePath is added to remote, but it is never assigned if there is an image to upload.
As this is also in master this might cause problems in the next release?

**Comment by LukeOwncloud** [comment]
@tobiasKaminsky :+1: Thanks!

**Comment by masensio** [comment]
Hi all!

@LukeOwncloud, @strugee, @tobiasKaminsky, I've checked with master branch, and I don't have any crash. Do I need to do any action before trying to share?

**Comment by tobiasKaminsky** [comment]
Master is working, you are right.
But on some commit someone implementent the "local.add()":
https://github.com/owncloud/android/blob/beta/src/com/owncloud/android/ui/activity/Uploader.java#L575
This results in L637 to adding an empty string to remote, which then leads to an execption (something like "remote path does not exist on creating OCfile).

I think you have added the part with local?

**Comment by tobiasKaminsky** [comment]
@LukeOwncloud please test it and reopen if not working.
Regarding the cause I suspect that this is just happening due to wrong merge by me ;)
