### ISSUE TITLE
Beta 20160124 crashes when opening a gif image.

### ISSUE THREAD

**Issue by elpraga** [owncloud/android#1452]
************ CAUSE OF ERROR ************

java.lang.ArithmeticException: divide by zero
	at com.owncloud.android.ui.preview.ImageViewCustom.onDraw(ImageViewCustom.java:81)
	at third_parties.michaelOrtiz.TouchImageViewCustom.onDraw(TouchImageViewCustom.java:287)
	at android.view.View.draw(View.java:13477)
	at android.view.View.buildDrawingCache(View.java:12738)
	at android.view.View.getDisplayList(View.java:12407)
	at android.view.View.getDisplayList(View.java:12472)
	at android.view.View.draw(View.java:13201)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
	at android.view.View.draw(View.java:13480)
	at android.view.View.getDisplayList(View.java:12428)
	at android.view.View.getDisplayList(View.java:12472)
	at android.view.View.draw(View.java:13201)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
	at android.view.View.draw(View.java:13480)
	at android.support.v4.view.ViewPager.draw(ViewPager.java:2262)
	at android.view.View.getDisplayList(View.java:12428)
	at android.view.View.getDisplayList(View.java:12472)
	at android.view.View.draw(View.java:13201)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1229)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
	at android.view.View.getDisplayList(View.java:12426)
	at android.view.View.getDisplayList(View.java:12472)
	at android.view.View.draw(View.java:13201)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
	at android.view.View.draw(View.java:13480)
	at android.widget.FrameLayout.draw(FrameLayout.java:467)
	at android.view.View.getDisplayList(View.java:12428)
	at android.view.View.getDisplayList(View.java:12472)
	at android.view.View.draw(View.java:13201)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
	at android.view.View.draw(View.java:13480)
	at android.support.v7.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:442)
	at android.view.View.getDisplayList(View.java:12428)
	at android.view.View.getDisplayList(View.java:12472)
	at android.view.View.draw(View.java:13201)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
	at android.view.View.getDisplayList(View.java:12426)
	at android.view.View.getDisplayList(View.java:12472)
	at android.view.View.draw(View.java:13201)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
	at android.view.View.getDisplayList(View.java:12426)
	at android.view.View.getDisplayList(View.java:12472)
	at android.view.View.draw(View.java:13201)
	at android.view.ViewGroup.drawChild(ViewGroup.java:2929)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2799)
	at android.view.View.draw(View.java:13480)
	at android.widget.FrameLayout.draw(FrameLayout.java:467)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2183)
	at android.view.View.getDisplayList(View.java:12428)
	at android.view.View.getDisplayList(View.java:12472)
	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1145)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2147)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2019)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1830)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:998)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4212)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
	at android.view.Choreographer.doCallbacks(Choreographer.java:555)
	at android.view.Choreographer.doFrame(Choreographer.java:525)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4745)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method)

************ DEVICE INFORMATION ***********
Brand: rk30sdk
Device: rk30sdk
Model: Woxter Tablet PC 97IPS DUAL
Id: JRO03H
Product: rk30sdk

************ FIRMWARE ************
SDK: 16
Release: 4.1.1
Incremental: eng.lsd.20120924.135651

**Comment by tobiasKaminsky** [comment]
Strange. 
It is working for me.
Can you try it with a different gif? 
(the gif must be downloaded of course to play it, otherwise it should show a regular thumbnail)

**Comment by elpraga** [comment]
The same gif working as expected now  in 20160305.
