### ISSUE TITLE
beta 20160120: Crash in file upload

### ISSUE THREAD

**Issue by dragotin** [owncloud/android#1465]
When uploading an image I get this backtrace:

```
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start service com.owncloud.android.files.services.FileUploader@30c1f5ba with Intent { cmp=com.owncloud.android.beta/com.owncloud.android.files.services.FileUploader (has extras) }: java.lang.IllegalArgumentException: Trying to create a OCFile with a non valid remote path: 
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2941)
    at android.app.ActivityThread.access$2100(ActivityThread.java:155)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5343)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
Caused by: java.lang.IllegalArgumentException: Trying to create a OCFile with a non valid remote path: 
    at com.owncloud.android.datamodel.OCFile.<init>(OCFile.java:103)
    at com.owncloud.android.files.services.FileUploader.obtainNewOCFileToUpload(FileUploader.java:771)
    at com.owncloud.android.files.services.FileUploader.onStartCommand(FileUploader.java:286)
    at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2924)
    ... 9 more

************ DEVICE INFORMATION ***********
Brand: motorola
Device: osprey_umts
Model: MotoG3
Id: LPI23.72-47.4
Product: osprey_reteu

************ FIRMWARE ************
SDK: 22
Release: 5.1.1
Incremental: 4
```

**Comment by tobiasKaminsky** [comment]
@dragotin 
Can you test the latest beta?

**Comment by strugee** [comment]
@tobiasKaminsky I'm not seeing an upgrade in F-Droid, any idea why? (Possibly their builder hasn't picked up the changes but I'm _pretty sure_ it's been 24 hours)

**Comment by tobiasKaminsky** [comment]
@strugee F-Droid has a problem with the latest 4-5 builds.
I have already asked on IRC.

**Comment by strugee** [comment]
@tobiasKaminsky gotcha. Thanks.

**Comment by strugee** [comment]
@tobiasKaminsky did you ever get a reply?

**Comment by tobiasKaminsky** [comment]
@strugee No, I have now asked again on IRC.

**Comment by CiaranG** [comment]
https://botbot.me/freenode/fdroid/2016-02-20/?msg=60522217&page=1

(in short, the build produces what appears to be an invalid apk file - odd though that seems)

**Comment by tobiasKaminsky** [comment]
@CiaranG Thank you.
But unfortunately I do not know how to fix it as the labels have to be resources as they are translated in all supported languages.
Maybe you can help me?

**Comment by tobiasKaminsky** [comment]
@dragotin is this still happening?

**Comment by strugee** [comment]
@tobiasKaminsky I could reproduce this, and can't anymore.

**Comment by davivel** [comment]
Beta process is going to change. Current beta branch will not be maintained anymore. If this is detected in a stable version, please reopen.

And thanks for reporting! :)
