### ISSUE TITLE
Cannot upload file from Google Drive

### ISSUE THREAD

**Issue by fornwall** [owncloud/android#1476]
Using version `1.9.1` of the app on the stock Android 6.0 on a Nexus 6P:

1. Navigate to a folder where you want to upload a file.
2. Press the Upload button.
3. Select `Content from other apps`.
4. Select `Drive` in the `Open from` navigation drawer.
5. Select the file to upload.

No file is uploaded, but the following exception is shown in `logcat`:

    Upload of content://com.google.android.apps.docs.storage/document/acc%3D1%3Bdoc%3D3179 to /Photos/hi.txt: Unrecovered transport exception
    java.io.FileNotFoundException: content:/com.google.android.apps.docs.storage/document/acc%3D1%3Bdoc%3D3179: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:452)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117)
	at com.owncloud.android.lib.common.network.FileRequestEntity.writeRequest(FileRequestEntity.java:109)
	at org.apache.commons.httpclient.methods.EntityEnclosingMethod.writeRequestBody(EntityEnclosingMethod.java:499)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2114)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:222)
	at com.owncloud.android.lib.resources.files.UploadRemoteFileOperation.uploadFile(UploadRemoteFileOperation.java:140)
	at com.owncloud.android.lib.resources.files.UploadRemoteFileOperation.run(UploadRemoteFileOperation.java:100)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
	at com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:329)
	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:574)
	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:522)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)
    Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:438)

**Comment by fornwall** [comment]
Does the owncloud app not support `content://` uri:s? A quick look at the code seems to indicate that it tries to resolve down to a local file path, which won't work in many cases - opening a content:// uri must be done through [ContentProvider#openFile()](http://developer.android.com/reference/android/content/ContentProvider.html#openFile(android.net.Uri, java.lang.String)).

**Comment by masensio** [comment]
Hi @fornwall,

thanks for your feedback.

I think we have a problem when trying to upload a file to owncloud from some apps as Drive. We are taking into account an incorrect path when catching the file, so we need to review this process and fix this problem.
We will take in mind this issue for our upload improvements.

Thanks for your tips for fixing the issue.

**Comment by davivel** [comment]
Sorry, @fornwall . I overlooked this issue, and @jesmrec found it again in our regression tests for release in progress.

If you don't mind, we will track the problem in #1607. Let me invite you to join there.
