### ISSUE TITLE
App stops working when trying to share a file while uploading it

### ISSUE THREAD

**Issue by gig13** [owncloud/android#1642]
### Expected behaviour
While uploading a relatively large file (100MB) and trying to share it before the upload completes, you should be able to share it, or get a message that you are unable to share until the upload completes.

### Actual behaviour
The app crashes and the upload notification remains in the notification

### Steps to reproduce
1) Upload a relatively large file (so you have time to replicate all the
steps below)

2) Go to the Android's native notification bar (swipe down the screen) and
tap into the owncloud's upload notification

3) You will be redirected to the application's upload view

4) Tap the settings button (the three vertical dots) and then the share
option

5) With the file still being uploaded, tap the "ADICIONAR USUÁRIO OU GRUPO"
(sorry, I don't know how it is set in english but it should be something
like "Add User or Group")

6) The app crashes and the upload notification remains in the notification
bar:
![app_crash](https://cloud.githubusercontent.com/assets/4803385/14864701/0ccc73c2-0c89-11e6-9fdc-fa4e91c8a1dc.jpeg)

To obtain following info
### Environment data
Android version:5.1

Device model: Moto G1

Stock or customized system: Stock

ownCloud app version: Terra_1.9.1.539-release.apk (1.9.1)

ownCloud server version: 8.2.2.2

@MorrisJobke @michaelstingl @rperezb 
I was unable to reproduce on my Android device: 
DROID TURBO 2
Android version 6.0
app version 2.0.0
server OC8.2.2

**Comment by LukeOwncloud** [comment]
I cannot reproduce with owncloud version 2.0.0 on Android 4.2.2. Main difference : step 3 - clicking upload notification opens new view showing list of current and completed uploads. The upload view you show in your sceeenshot is not available for me. I also noticed that the owncloud symbol in your notification bar looks different than mine (I don't have the up arrow within the cloud symbol). 
Which owncloud app version are you using? 
Your last paragraph (cannot reproduce) is confusing.

**Comment by MorrisJobke** [comment]
@gig13 At least it would be nice to know the version where this happens. Could you try to get that information?

**Comment by gig13** [comment]
@MorrisJobke I am trying to get the info

**Comment by gig13** [comment]
@MorrisJobke Added device info

Android version:5.1

Device model: Moto G1

Stock or customized system: Stock

ownCloud app version: Terra_1.9.1.539-release.apk (1.9.1)

ownCloud server version: 8.2.2.2

**Comment by MorrisJobke** [comment]
@gig13 there are now two ways:

* they upgrade the Android app
* we try to reproduce with 1.9.1

@gig13 could you try the second one? If it works there, we need to investigate further, why it is working here and not on their side. If it is not working, then they should upgrade.

**Comment by gig13** [comment]
@rperezb Can you reproduce steps 3-5... I do not have those screens showing up as stated.

**Comment by rperezb** [comment]
@gig13 yes, I reproduced it in 1.9.1, let me check it against the current version, 2.0.0

LOGS:
```
05-06 13:42:28.640 9733-9733/xxx.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             java.lang.NullPointerException
                                                                                 at com.xxxx.android.ui.fragment.SearchShareesFragment.refreshUsersOrGroupsListFromDB(SearchShareesFragment.java:166)
                                                                                 at com.xxxx.android.ui.fragment.SearchShareesFragment.onActivityCreated(SearchShareesFragment.java:153)
                                                                                 at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1797)
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:979)
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
                                                                                 at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
                                                                                 at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
                                                                                 at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:458)
                                                                                 at android.os.Handler.handleCallback(Handler.java:615)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                                 at android.os.Looper.loop(Looper.java:137)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:4898)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
                                                                                 at dalvik.system.NativeStart.main(Native Method)
05-06 13:42:28.710 2241-2343/? E/android.os.Debug: !@Dumpstate > dumpstate -k -t -z -d -o /data/log/dumpstate_app_error
05-06 13:42:28.735 18006-18006/? I/dumpstate: begin
```

**Comment by rperezb** [comment]
within 2.0.0 this crash is not possible to be reproduce (at least, I can't)

When you tap on the upload notification, you are lead to the uploads view, from there it's not possible to share the file or do any other action but cancel the upload

@gig13 can you please let them to check agains 2.0.0 (they do have it already available to be downloaded)

**Comment by gig13** [comment]
@rperezb Awesome, thanks!

**Comment by rperezb** [comment]
@gig13 💃
