### ISSUE TITLE
IllegalArgumentException while opening "Uploads" from the left drawer

### ISSUE THREAD

**Issue by dniku** [owncloud/android#1713]
```
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.owncloud.android/com.owncloud.android.ui.activity.UploadListActivity}: java.lang.IllegalArgumentException: Compa
                                                            rison method violates its general contract!
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at android.app.ActivityThread.-wrap11(ActivityThread.java)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at android.os.Handler.dispatchMessage(Handler.java:102)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at android.os.Looper.loop(Looper.java:148)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at android.app.ActivityThread.main(ActivityThread.java:5466)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at java.lang.reflect.Method.invoke(Native Method)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at java.util.TimSort.mergeHi(TimSort.java:882)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at java.util.TimSort.mergeAt(TimSort.java:499)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at java.util.TimSort.mergeForceCollapse(TimSort.java:440)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at java.util.TimSort.sort(TimSort.java:219)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at java.util.TimSort.sort(TimSort.java:169)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at java.util.Arrays.sort(Arrays.java:2010)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter$2.refresh(ExpandableUploadListAdapter.java:151)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter.loadUploadItemsFromDb(ExpandableUploadListAdapter.java:590)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter.<init>(ExpandableUploadListAdapter.java:173)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at com.owncloud.android.ui.fragment.UploadListFragment.onStart(UploadListFragment.java:102)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at android.support.v4.app.Fragment.performStart(Fragment.java:1986)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1102)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2047)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:176)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:553)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at com.owncloud.android.ui.activity.FileActivity.onStart(FileActivity.java:262)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at android.app.Activity.performStart(Activity.java:6268)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
06-13 12:49:06.581  31446    31446         AndroidRuntime  E  ... 9 more
06-13 12:49:06.585   1151     3648        ActivityManager  W  Force finishing activity com.owncloud.android/.ui.activity.UploadListActivity
06-13 12:49:06.588   1151     3648        ActivityManager  W  Force finishing activity com.owncloud.android/.ui.activity.FileDisplayActivity
```

See here: https://github.com/owncloud/android/blob/dab4ef4550812f52a30d8a367d8ef30a1e9625ac/src/com/owncloud/android/ui/adapter/ExpandableUploadListAdapter.java#L151
### Steps to reproduce
1. Install client version 2.0.1 from F-Droid & open it
2. Open left drawer
3. Tap on "Uploads"
### Environment data

Android version: 6

Device model: Wileyfox Swift

Stock or customized system: CyanogenMod 13

ownCloud app version: 2.0.1

**Comment by jesmrec** [comment]
Upload shortcut changed its location. not reproducible
