### ISSUE TITLE
Crash in SAML when authenticate

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#1719]
Behaviour in `master` branch

### Steps to reproduce
1. Login in a SAML server inputing credentials

### Actual behaviour

App crashes

`06-23 10:05:21.025 8824-8843/com.owncloud.android D/GetRemoteUserInfoOperation: Successful response: {"ocs":{"meta":{"status":"ok","statuscode":100,"message":null},"data":{"id":"myself@testshib.org","display-name":"myself@testshib.org","email":"myself@testshib.org"}}}
06-23 10:05:21.027 8824-8824/com.owncloud.android D/AndroidRuntime: Shutting down VM
06-23 10:05:21.028 8824-8824/com.owncloud.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.owncloud.android, PID: 8824
                                                                    java.lang.ClassCastException: com.owncloud.android.lib.resources.users.GetRemoteUserInfoOperation$UserInfo cannot be cast to java.lang.String
                                                                        at com.owncloud.android.authentication.AuthenticatorActivity.onGetUserNameFinish(AuthenticatorActivity.java:1044)
                                                                        at com.owncloud.android.authentication.AuthenticatorActivity.onRemoteOperationFinish(AuthenticatorActivity.java:1035)
                                                                        at com.owncloud.android.services.OperationsService$1.run(OperationsService.java:785)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-23 10:05:21.030 8824-8843/com.owncloud.android D/OperationsService: Called 1 listeners
06-23 10:05:21.043 8824-8843/com.owncloud.android D/OperationsService: Stopping after command with id 2
06-23 10:05:37.143 10539-10539/com.owncloud.android W/System: ClassLoader referenced unknown path: /data/app/com.owncloud.android-1/lib/arm
06-23 10:05:37.215 10539-10549/com.owncloud.android W/art: Suspending all threads took: 6.784ms`

### Expected behaviour

App logins correctly
 

### Environment data
Android version: v4.3, v4,4,2, v5 and v6 

Servers 8.2, 9.0 and 9.1

------- edited by @jabarros

TASKS
- [x] [GIT] Create `fix_shiboled_display_name` branch from master in android repo @jabarros
- [x] [DEV] Get display name when userInfo object @jabarros
- [X] [QA] Create `fix_shiboled_display_name` branch from master in QA repo -> not needed @jesmrec
- [X] [QA] Merge `fix_shiboled_display_name` branch into master in QA repo  -> not needed @jesmrec
- [X] [QA] Create test plan  -> not needed @jesmrec
- [X] [QA] Validate test plan @jesmrec
- [X] [GIT] Merge `fix_shiboled_display_name` branch into master in android repo

This bug is absolutely located and only causes problem in a determinate case. No test plan / QA branch is needed.

**Comment by jabarros** [comment]
Fixed in #1720

**Comment by jesmrec** [comment]
Approved

**Comment by jabarros** [comment]
#1720 meged
