### ISSUE TITLE
Unable to share files

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/android#1734]
### Actual behaviour
- After select share option on a file or folder , we are not able to find any user to share. Does not matter local users or fed share.

### Expected behaviour
- After select share option on a file or folder, we should be able to find users and share the item with them.
 
### Steps to reproduce
1.  Long touch on a file or folder
2.  Select Share option
3.  Type a user or user@remote

Can this problem be reproduced with the official owncloud server?
yes

### Environment data
Android version: 5.0.1

Device model: Nexus 5

ownCloud app version: 2.0.1

ownCloud server version: 9.1.0 RC1

### Logs
`07-07 08:47:20.636 29948-30634/com.owncloud.android E/ActivityThread: Failed to find provider info for com.owncloud.android.providers.UsersAndGroupsSearchProvider
`

____

BUGS & IMPROVEMENTS

- [ ] No results returned https://github.com/owncloud/android/issues/1734#issuecomment-235635822  [READY_TO_TEST]

**Comment by payam-huemer** [comment]
I have the same issue with the same log on 
android version: 6.0
App version: 2.01
owncloud server: 8.2

**Comment by davivel** [comment]
Ooooh, right. Probably because of #1735 . Makes sense. 

I'll go for this ASAP.

**Comment by davivel** [comment]
Wait, no... but that shouldn't happen with 2.0.1 version...

**Comment by payam-huemer** [comment]
@davivel I changed the  android:authorities=".providers.UsersAndGroupsSearchProvider" to  +             android:authorities="com.owncloud.android.providers.UsersAndGroupsSearchProvider" and it's working for me now.

**Comment by davivel** [comment]
Thanks, @payam-huemer , I expected that. I was doubting because the 2.0.1 version in Play Store should have the full authority string. I guess you built the app by yourself, right?

**Comment by payam-huemer** [comment]
@davivel Yes, I am building it myself based on the master branch.

**Comment by jesmrec** [comment]
@davivel 

When i try to search for users, no result is returned. This stack trace is output:

`07-27 17:49:05.398 19776-21835/com.owncloud.android W/SuggestionsAdapter: Search suggestions query threw an exception.
                                                                          java.lang.NullPointerException
                                                                              at com.owncloud.android.providers.UsersAndGroupsSearchProvider.query(UsersAndGroupsSearchProvider.java:157)
                                                                              at android.content.ContentProvider.query(ContentProvider.java:857)
                                                                              at android.content.ContentProvider$Transport.query(ContentProvider.java:200)
                                                                              at android.content.ContentResolver.query(ContentResolver.java:461)
                                                                              at android.content.ContentResolver.query(ContentResolver.java:404)
                                                                              at android.support.v7.widget.SuggestionsAdapter.getSearchManagerSuggestions(SuggestionsAdapter.java:754)
                                                                              at android.support.v7.widget.SuggestionsAdapter.runQueryOnBackgroundThread(SuggestionsAdapter.java:157)
                                                                              at android.support.v4.widget.CursorFilter.performFiltering(CursorFilter.java:50)
                                                                              at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:136)
                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)`


Branch `customizable_users_search_provder`
Tested with MotoE v4.4. Nexus5 v5.0.1
Server 9.1

**Comment by davivel** [comment]
Bug on the bug; I'll check it tomorrow.

**Comment by davivel** [comment]
Instant Run is breaking the initialization.

```
07-28 09:14:39.357 8849-8849/com.owncloud.android E/TAG: Fail creating provider
                                                         java.lang.ClassCastException: com.android.tools.fd.runtime.BootstrapApplication cannot be cast to com.owncloud.android.MainApp
                                                             at com.owncloud.android.providers.UsersAndGroupsSearchProvider.onCreate(UsersAndGroupsSearchProvider.java:112)
...
```

I'll rewrite so that it works with or without it

**Comment by davivel** [comment]
@jesmrec , bug ready to test.

**Comment by jesmrec** [comment]
Approved in PR #1749 

cc @davivel
