### ISSUE TITLE
[Crash market] Crash related to uploads

### ISSUE THREAD

**Issue by rperezb** [owncloud/android#1748]
- Crash on the market, this is being reproduced many times specially within the latest version 2.0.1

### DEVICES
- It's reproduced on Android6 more frecuently

### LOGS
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.owncloud.android/com.owncloud.android.ui.activity.UploadListActivity}: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
	at android.app.ActivityThread.access$1100(ActivityThread.java:222)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:882)
	at java.util.TimSort.mergeAt(TimSort.java:499)
	at java.util.TimSort.mergeForceCollapse(TimSort.java:440)
	at java.util.TimSort.sort(TimSort.java:219)
	at java.util.TimSort.sort(TimSort.java:169)
	at java.util.Arrays.sort(Arrays.java:2010)
	at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter$2.refresh(ExpandableUploadListAdapter.java:151)
	at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter.loadUploadItemsFromDb(ExpandableUploadListAdapter.java:590)
	at com.owncloud.android.ui.adapter.ExpandableUploadListAdapter.<init>(ExpandableUploadListAdapter.java:173)
	at com.owncloud.android.ui.fragment.UploadListFragment.onStart(UploadListFragment.java:102)
	at android.support.v4.app.Fragment.performStart(Fragment.java:1986)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1102)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1230)
	at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2047)
	at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:176)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:553)
	at com.owncloud.android.ui.activity.FileActivity.onStart(FileActivity.java:262)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1265)
	at android.app.Activity.performStart(Activity.java:6915)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3217)
	... 9 more
```

**Comment by davivel** [comment]
Should be fixed now in branch release_2.1.0, as part of #1750
