### ISSUE TITLE
App crash on refresh

### ISSUE THREAD

**Issue by ido1990** [owncloud/android#1838]
### Actual behaviour
The app crashes when refreshing (or loading to show files)

### Expected behaviour
Just work.
 
### Steps to reproduce
1. Lunch the app
2. Refresh to get the files list
3. Crash

Can this problem be reproduced with the official owncloud server? No, it's working fine.
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version: down in the log

Device model: down in the log

Stock or customized system: stock

ownCloud app version: Beta 20160606

ownCloud server version: 9.1.2

### From the beta app
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.owncloud.android.lib.common.operations.RemoteOperationResult)
at android.os.Parcel.writeSerializable(Parcel.java:1468)
at android.os.Parcel.writeValue(Parcel.java:1416)
at android.os.Parcel.writeArrayMapInternal(Parcel.java:686)
at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330)
at android.os.Bundle.writeToParcel(Bundle.java:1079)
at android.os.Parcel.writeBundle(Parcel.java:711)
at android.content.Intent.writeToParcel(Intent.java:7793)
at android.app.ActivityManagerProxy.broadcastIntent(ActivityManagerNative.java:3043)
at android.app.ContextImpl.sendStickyBroadcast(ContextImpl.java:1016)
at android.content.ContextWrapper.sendStickyBroadcast(ContextWrapper.java:509)
at com.owncloud.android.operations.RefreshFolderOperation.sendLocalBroadcast(RefreshFolderOperation.java:519)
at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:208)
at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:303)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.NotSerializableException: org.apache.harmony.xml.dom.ElementImpl
at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
at android.os.Parcel.writeSerializable(Parcel.java:1463)
... 13 more

************ DEVICE INFORMATION ***********
Brand: google
Device: hammerhead
Model: Nexus 5
Id: MOB30M
Product: hammerhead

************ FIRMWARE ************
SDK: 23
Release: 6.0.1
Incremental: 2862625

**Comment by davivel** [comment]
Hi, @ido1990 . Could you check if there is an error in the logs of the server when you try to refresh in the Android app?. I think that the exception might be hiding another exception encapsulated in the result object, would be useful to know what's the original error.

**Comment by ido1990** [comment]
@davivel
I just opened the app to try to recreate the error and it's just working and no errors in the server log.
So I guess I'll close it for now.

**Comment by davivel** [comment]
Thanks, @ido1990 . Just write here again if reappears.
