### ISSUE TITLE
Instant Upload fails with “Unknown error”

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#1879]
### Actual behaviour
The upload aborts between 35 and 40% with "Unknown error". Retry is not successful.

### Expected behaviour
Instant Upload should send the picture to the OwnCloud server without an error.
 
### Steps to reproduce
1. Take a new picture with the Camera application.

### Environment data
Android version: 6.0.1 

Device model: Nexus 5

Stock or customized system: Stock

ownCloud app version: 2.2.0

ownCloud server version: 9.1.2

#### Web server error log
```
{"reqId":"XXX","remoteAddr":"","app":"core","message":"starting upgrade from 8.2.1.4 to 9.0.6.5","level":0,"time":"2016-11-18T00:59:09+00:00","method":"--","url":"--","user":"--"}
{"reqId":"XXX","remoteAddr":"","app":"core","message":"No update found at the ownCloud appstore for app XXX","level":0,"time":"2016-11-18T00:59:19+00:00","method":"--","url":"--","user":"--"}
{"reqId":"XXX","remoteAddr":"X.X.X.X","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in maintenance mode.\",\"Exception\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\EmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2\\\/Server.php(446): Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3\\\Server.php(248): >invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4\\\/appinfo\\\/v1\\\/webdav.php(55)\\Server->exec()\\n#5 /remote.php(138('18T01:00:15+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","user":"XXX"}
{"reqId":"XXX+w\/9OG","remoteAddr":"","app":"core","message":"starting upgrade from 9.0.6.5 to 9.1.2.5","level":0,"time":"2016-11-18T01:19:29+00:00","method":"--","url":"--","user":"--"}
{"reqId":"XXX","remoteAddr":"X.X.X.X.","app":"PHP","message":"fopen(/test.png): failed to open stream: No such file or directory at /Local.php#278","level":3,"time":"2016-11-29T17:46:28+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/preview.png?file=%XXXXX","user":"XXX"}
{"reqId":"XXX","remoteAddr":"X.X.X.X","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-12-31T03:19:44+00:00","method":"POST","url":"\/owncloud\/index.php\/heartbeat","user":"--"}
{"reqId":"XXX","remoteAddr":"X.X.X.X","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'INSERT INTO \\\"oc_file_locks\\\" (\\\"key\\\",\\\"lock\\\",\\\"ttl\\\") SELECT ?,?,? FROM \\\"oc_file_locks\\\" WHERE \\\"key\\\" = ? HAVING COUNT(*) = 0' with params [\\\"files\\\\\\\/xxx\\\", 1, 1483563027, \\\"files\\\\\\\/xxx\\\"]:\\n\\nSQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \\\"lock_key_index\\\"\\nDETAIL:  Key (key)=(files\\\/xxx) already exists.\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\UniqueConstraintViolationException\",\"Code\":0,\"Trace\":\"#0
```

#### ownCloud log (data/owncloud.log)
```
Starting content synchronization... 
RemoteOperationResult has processed UNHANDLED_HTTP_CODE: 502
Received broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_CONTENTS_SYNCED
Upload of /storage/emulated/0/Pictures/test.png to /test.png: Operation finished with HTTP status code 502 (fail)
```

**Comment by bkraul** [comment]
Any news on this? All other owncloud clients work perfectly. I have even used Cadaver to test uploads and they all work fine. The problem is only with the android app.

**Comment by davivel** [comment]
> All other owncloud clients work perfectly

**Comment by bkraul** [comment]
I do not own an iOS device at the moment, so I couldn't say, but yes, the desktop client works just fine, and so does interacting with the Sabre server through tools like Cadaver from both windows, and from linux. I am able to upload files and create directories.

I attached to a couple of these issues here in github when I started having "Unknown Error" issues from the android app. I am not familiar with existing related issues at central.owncloud.org.

I also asummed a failed upgrade would be the case, so I perfomed a repair (using occ), which did not resolve the issue, followed by a clean install. I actually initially upgraded from 9.1.2 to 9.1.3 stable.

Here is the complete sequence of events from the log when the file upload fails. The funny thing is there is no other error I can see other than an httpd 500 notice on the PUT action (always at 1657) which gives me no information. I can see that it gets to a certain number of bytes and then it stops.

Apache access log (in tail order):
```
[mobile ip]   - - [03/Feb/2017:09:33:19 -0600] "HEAD /remote.php/webdav/InstantUpload/ HTTP/1.1" 401 137 "-" "Mozilla/5.0 (Android) ownCloud-android/2.2.0"
[mobile ip]   - - [03/Feb/2017:09:33:19 -0600] "HEAD /remote.php/webdav/InstantUpload/ HTTP/1.1" 200 758 "-" "Mozilla/5.0 (Android) ownCloud-android/2.2.0"
[mobile ip]   - - [03/Feb/2017:09:33:19 -0600] "HEAD /remote.php/webdav/InstantUpload/20170203_070837.jpg HTTP/1.1" 401 700 "-" "Mozilla/5.0 (Android) ownCloud-android/2.2.0"
[mobile ip]   - - [03/Feb/2017:09:33:19 -0600] "HEAD /remote.php/webdav/InstantUpload/20170203_070837.jpg HTTP/1.1" 404 758 "-" "Mozilla/5.0 (Android) ownCloud-android/2.2.0"
[mobile ip]   - - [03/Feb/2017:09:33:20 -0600] "PUT /remote.php/webdav/InstantUpload/20170203_070837.jpg-chunking-7914-3-0 HTTP/1.1" 500 1657 "-" "Mozilla/5.0 (Android) ownCloud-android/2.2.0"
[mobile ip]   - - [03/Feb/2017:09:33:31 -0600] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 4486 "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 6408)"
```
Owncloud log (in cat order)
```

{"reqId":"WJSitK1J@OcKdjLh2V7ckQAAAAg","remoteAddr":"[mobile ip]","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/remote.php(164): require_once('\\\/var\\\/www\\\/client...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":\"bkraul\"}","level":0,"time":"2017-02-03T15:33:08+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"bkraul"}
{"reqId":"WJSiv9GgOsJLy9OZiig3VwAAAAw","remoteAddr":"[mobile ip]","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/remote.php(164): require_once('\\\/var\\\/www\\\/client...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":\"bkraul\"}","level":0,"time":"2017-02-03T15:33:19+00:00","method":"HEAD","url":"\/remote.php\/webdav\/InstantUpload\/","user":"bkraul"}
{"reqId":"WJSiv9GgOsJLy9OZiig3WQAAAAw","remoteAddr":"[mobile ip]","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/remote.php(164): require_once('\\\/var\\\/www\\\/client...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":\"bkraul\"}","level":0,"time":"2017-02-03T15:33:19+00:00","method":"HEAD","url":"\/remote.php\/webdav\/InstantUpload\/20170203_070837.jpg","user":"bkraul"}
{"reqId":"WJSiv9GgOsJLy9OZiig3WgAAAAw","remoteAddr":"[mobile ip]","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name InstantUpload\\\/20170203_070837.jpg could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(79): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('InstantUpload\\\/2...', 0)\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(251): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response), false)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpHead(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:HEAD', Array)\\n#8 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248):
Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/remote.php(164): require_once('\\\/var\\\/www\\\/client...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":170,\"User\":\"bkraul\"}","level":0,"time":"2017-02-03T15:33:19+00:00","method":"HEAD","url":"\/remote.php\/webdav\/InstantUpload\/20170203_070837.jpg","user":"bkraul"}
{"reqId":"WJSiwNGgOsJLy9OZiig3WwAAAAw","remoteAddr":"[mobile ip]","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/remote.php(164): require_once('\\\/var\\\/www\\\/client...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/clients\\\/client1\\\/web1\\\/web\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":\"bkraul\"}","level":0,"time":"2017-02-03T15:33:21+00:00","method":"PUT","url":"\/remote.php\/webdav\/InstantUpload\/20170203_070837.jpg-chunking-7914-3-0","user":"bkraul"}
```

Now, I had not pasted much of this on the log because I read that Authorization: Basic header errors are 'normal', and didn't think they would be of consequence.

**Comment by PVince81** [comment]
I have a similar issue randomly, without instant upload.

My steps / my workflow:

1. Take a bunch of pictures with the Camera app
1. Go to the ownCloud app
1. Navigate into the  folder "umstiegstation"
1. Select the "upload" function
1. Navigate into the DCIM/Camera folder
1. Select pics to upload and select "move" instead of "copy"
1. Accept upload

Most pictures will upload fine, but from times to times one picture in the batch fails with "Unknown error".
In my posted case the picture is "IMG_20170204_080021.jpg". I've observed this behavior already 5-6 times before in previous uploads many weeks ago.

Looking at the server is similar to what @bkraul observed in https://github.com/owncloud/android/issues/1879#issuecomment-277279823

```
{"reqId":"WJWc9n8AAAIAAFAaSmcAAAAG","remoteAddr":"85.180.4.189","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n
#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(57): Sabre\\\\DAV\\\\Server->exec()\\n
#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(164): require_once('\\\/srv\\\/www\\\/htdocs...')\\n
#6 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":\"vincent\"}","level":0,"time":"2017-02-04T09:20:54+00:00","method":"HEAD","url":"\/remote.php\/webdav\/clientsync\/petry\/pics\/umstiegstation\/IMG_20170204_080021.jpg","user":"vincent"}
{"reqId":"WJWc9n8AAAIAAFAaSmgAAAAG","remoteAddr":"85.180.4.189","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name clientsync\\\/petry\\\/pics\\\/umstiegstation\\\/IMG_20170204_080021.jpg could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(79): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('clientsync\\\/petr...', 0)\\n
#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n
#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(251): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response), false)\\n
#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpHead(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:HEAD', Array)\\n
#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#9 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(57): Sabre\\\\DAV\\\\Server->exec()\\n
#10 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(164): require_once('\\\/srv\\\/www\\\/htdocs...')\\n
#11 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":170,\"User\":\"vincent\"}","level":0,"time":"2017-02-04T09:20:54+00:00","method":"HEAD","url":"\/remote.php\/webdav\/clientsync\/petry\/pics\/umstiegstation\/IMG_20170204_080021.jpg","user":"vincent"}
{"reqId":"WJWc9n8AAAIAAFAaSmkAAAAG","remoteAddr":"85.180.4.189","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"
#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n
#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(57): Sabre\\\\DAV\\\\Server->exec()\\n
#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(164): require_once('\\\/srv\\\/www\\\/htdocs...')\\n
#6 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":\"vincent\"}","level":0,"time":"2017-02-04T09:20:54+00:00","method":"PUT","url":"\/remote.php\/webdav\/clientsync\/petry\/pics\/umstiegstation\/IMG_20170204_080021.jpg-chunking-5832-2-0","user":"vincent"}
{"reqId":"WJWdCH8AAAIAAFAaSmsAAAAG","remoteAddr":"85.180.4.189","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"
#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#2 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n
#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(57): Sabre\\\\DAV\\\\Server->exec()\\n
#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(164): require_once('\\\/srv\\\/www\\\/htdocs...')\\n
#6 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":\"vincent\"}","level":0,"time":"2017-02-04T09:21:13+00:00","method":"PUT","url":"\/remote.php\/webdav\/clientsync\/petry\/pics\/umstiegstation\/IMG_20170204_080021.jpg-chunking-5832-2-1","user":"vincent"}
```

My server was 9.1.4 RC2 at the time the issue was observed.

The 404 is expected: the Android client first sends a HEAD request to find out whether the remote file already exists, to detect conflicts. Once it got a 404 it knows it can safely upload.

The part that looks wrong here is that it gets a 401 error when uploading the second chunk.
I do not get a 500 error though.

@davivel can you confirm that for every uploaded chunk the Android client will reuse the current session ? Or does it attempt basic auth for every chunk ? If the latter, could be the "cookie test issue we talked about". But even then, the basic auth should succeed and the next chunk should be uploaded.

**Comment by PVince81** [comment]
Ah, in my case retry is successful. I hope we're talking about the same issue. I'm fine making a separate ticket if the issue still exists for you @bkraul with the newly released 9.1.4.

**Comment by PVince81** [comment]
and... additional details: I'm using a token for authentication, not my actual password.

**Comment by bkraul** [comment]
For reference. I removed all owncloud data (database, files, etc), and reinstalled 9.1.4 from scratch following the latest installation guidelines. Granted I lost all my revision history, everything else works now, including the Android app.

**Comment by davivel** [comment]
@bkraul , thank you very much for your feedback, even after fixing the bug by yourself. I'm really sorry I didn't help you before.

> @davivel can you confirm that for every uploaded chunk the Android client will reuse the current session ? 

The session is used from version 2.2.0 of the app, not before. Can you confirm you still have the bug with 2.2.0 or 2.3.0? 

I still need you remind me what's the "cookie test issue we talked about" , if you have a link or some time...

**Comment by davivel** [comment]
@davigonz , what was the source of the **original** request in the first comment of the issue? A thread in central.owncloud.org? Could you include the link there, please?

**Comment by davigonz** [comment]
@davivel Sorry but If I remember well, there isn't any thread in central.owncloud.org about this, I found out this bug while I was working on other issue.

**Comment by davivel** [comment]
@PVince81 , do you remember this one? : 

>> @davivel can you confirm that for every uploaded chunk the Android client will reuse the current session ?
>
> The session is used from version 2.2.0 of the app, not before. Can you confirm you still have the bug with 2.2.0 or 2.3.0?
>
>I still need you remind me what's the "cookie test issue we talked about" , if you have a link or some time...

**Comment by PVince81** [comment]
https://github.com/owncloud/core/issues/26651

**Comment by davivel** [comment]
Thanks.

**Comment by jesmrec** [comment]
Instant uploads became camera uploads some time ago, so the problem reported here should not happen anymore. In case it happens, it will be caused by a different problem. Feel free to reopen if you notice the problem persists.
