### ISSUE TITLE
Adapt app for hidden status.php

### ISSUE THREAD

**Issue by davivel** [owncloud/android#1931]
Public access to status.php file will be optional in a short time. Android app should be able to work correctly in this situation. At least we'll need to:

 - [x] Update login progress to avoid reading status.php before authenticating the user.
 - [x] Update operation of the app after log-in to check updates of OC version from capabilities API.

Related to: https://github.com/owncloud/core/pull/27473

- BUGS & IMPROVEMENTS

- [X] App crashes when SAML session expires https://github.com/owncloud/android/issues/1931#issuecomment-293304188 [FIXED]

**Comment by davivel** [comment]
@jesmrec , ready to be tested.

**Comment by jesmrec** [comment]
### Bug

Steps:

1. Login in a SAML server
2. Wait until session expires

Current behaviour

App crashes. Stack trace: 

04-11 17:20:00.357 20923-20952/com.owncloud.android E/AndroidRuntime: FATAL EXCEPTION: Thread-2
                                                                      Process: com.owncloud.android, PID: 20923
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.ArrayList.get(int)' on a null object reference
                                                                          at com.owncloud.android.operations.SyncCapabilitiesOperation.run(SyncCapabilitiesOperation.java:64)
                                                                          at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:118)
                                                                          at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:72)
                                                                          at com.owncloud.android.operations.RefreshFolderOperation.syncCapabilitiesAndGetServerVersion(RefreshFolderOperation.java:172)
                                                                          at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:125)
                                                                          at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:302)
                                                                          at java.lang.Thread.run(Thread.java:761)

Expected behaviour

Session expires and user is redirected to login view. 

Android7
Server 10.0beta2

@davivel

**Comment by davivel** [comment]
@jesmrec , bug ready to test.

**Comment by jesmrec** [comment]
Fixed and approved
