### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by lingling-fan** [owncloud/android#2031]
//package name: com.owncloud.android
//version: 2.2.0
//target sdk version: android-18
 java.lang.StringIndexOutOfBoundsException: length=10; regionStart=11; regionLength=-1
 	at java.lang.String.startEndAndLength(String.java:583)
 	at java.lang.String.substring(String.java:1464)
 	at com.owncloud.android.utils.DisplayUtils.convertIdn(DisplayUtils.java:178)
 	at com.owncloud.android.authentication.AuthenticatorActivity.checkOcServer(AuthenticatorActivity.java:834)
 	at com.owncloud.android.authentication.AuthenticatorActivity.onUrlInputFocusLost(AuthenticatorActivity.java:813)
 	at com.owncloud.android.authentication.AuthenticatorActivity.onFocusChange(AuthenticatorActivity.java:788)
 	at android.view.View.onFocusChanged(View.java:4640)
 	at android.widget.TextView.onFocusChanged(TextView.java:7551)
 	at android.view.View.unFocus(View.java:4561)
 	at android.view.ViewGroup.unFocus(ViewGroup.java:816)
 	at android.view.ViewGroup.requestChildFocus(ViewGroup.java:613)
 	at android.view.ViewGroup.requestChildFocus(ViewGroup.java:619)
 	at android.view.View.handleFocusGainInternal(View.java:4412)
 	at android.view.View.requestFocusNoSearch(View.java:6775)
 	at android.view.View.requestFocus(View.java:6754)
 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3857)
 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3774)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3483)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3540)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3516)
 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3666)
 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:1982)
 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1698)
 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1689)
 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:1959)
 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
 	at android.os.MessageQueue.nativePollOnce(Native Method)
 	at android.os.MessageQueue.next(MessageQueue.java:132)
 	at android.os.Looper.loop(Looper.java:124)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)

**Comment by jesmrec** [comment]
@eileenfan could you please detail the steps to reproduce the problem?
