### ISSUE TITLE
App crashes after update from 1.7.1 to 2.4

### ISSUE THREAD

**Issue by squao** [owncloud/android#2041]
### Actual behaviour

Install a new version  oc-android-2.4.0 on oc-android-1.7.1_signed but when I open new version it crashes straight away.

### Expected behaviour

App opens normally reusing existing configuration from the older version.

 
### Steps to reproduce
1. git checkout oc-android-1.7.1_signed
2. git submodule init
3. git submodule update
4. jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore /root/git/android/old_releasek
ey.keystore /root/git/android.old/build/outputs/apk/android.old-release-unsigned.apk releasekey
5. ./gradlew clean build
6. git checkout oc-android-2.4.0
7. git submodule init
8. git submodule update
9. git checkout oc-android-2.4.0
10. git submodule init
11. git submodule update
12. ./gradlew clean build
13. jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore /root/git/android/old_releasek
ey.keystore /root/git/android.old/build/outputs/apk/android.old_2.4.0-release-unsigned.apk releasekey

### Environment data
Android version: 7

Device model:  Huawai P9 lite

Stock or customized system:
Stock

ownCloud app version:
oc-android-1.7.1_signed > oc-android-2.4.0

ownCloud server version:
9.1.4.2

### Logs

```
10-09 14:49:53.125 25792 25792 E AndroidRuntime: FATAL EXCEPTION: main
10-09 14:49:53.125 25792 25792 E AndroidRuntime: Process: com.owncloud.android, PID: 25792
10-09 14:49:53.125 25792 25792 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.owncloud.android/com.owncloud.android.ui.activity.FileDisplayActivity}: android.database.sqlite.SQLiteException: duplicate column name: sharing_public_multiple (Sqlite code 1): , while compiling: ALTER TABLE capabilities ADD COLUMN sharing_public_multiple INTEGER  DEFAULT -1, (OS error - 2:No such file or directory)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:156)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6523)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: duplicate column name: sharing_public_multiple (Sqlite code 1): , while compiling: ALTER TABLE capabilities ADD COLUMN sharing_public_multiple INTEGER  DEFAULT -1, (OS error - 2:No such file or directory)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:910)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:521)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:603)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:63)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1965)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1890)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at com.owncloud.android.providers.FileContentProvider$DataBaseHelper.onUpgrade(FileContentProvider.java:836)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:272)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:199)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at com.owncloud.android.providers.FileContentProvider.query(FileContentProvider.java:352)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.content.ContentProvider.query(ContentProvider.java:1020)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:541)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:476)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at com.owncloud.android.datamodel.FileDataStorageManager.getCapabilityCursorForAccount(FileDataStorageManager.java:1973)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at com.owncloud.android.datamodel.FileDataStorageManager.getCapability(FileDataStorageManager.java:1996)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at com.owncloud.android.ui.activity.BaseActivity.onAccountSet(BaseActivity.java:156)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at com.owncloud.android.ui.activity.FileDisplayActivity.onAccountSet(FileDisplayActivity.java:273)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at com.owncloud.android.ui.activity.BaseActivity.onStart(BaseActivity.java:192)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at com.owncloud.android.ui.activity.FileActivity.onStart(FileActivity.java:174)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at com.owncloud.android.ui.activity.FileDisplayActivity.onStart(FileDisplayActivity.java:250)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1254)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:6930)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2756)
10-09 14:49:53.125 25792 25792 E AndroidRuntime: 	... 9 more
```

**Comment by jesmrec** [comment]
Old upgrades, currently in 2.10. 

If you experience problems with upgrading, please reopen or open a new issue.
