### ISSUE TITLE
AS 3.0 with Gradle  dependency file

### ISSUE THREAD

**Issue by NZOzzDeveloper** [owncloud/android#2096]
### Actual behaviour
-Setting up project for the first time, apologise if this is a "newbie" error and I have not done something I should have.  I have followed the setup documentation twice. 

done a clean and a rebuild of the project. 

Looked at the gradle dependencies.  
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'android-master'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:94)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:89)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:76)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectEvaluator.java:33)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:53)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEvaluator.java:50)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:50)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:628)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:129)
	at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:36)
	at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:161)
	at org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:158)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:158)

### Expected behaviour
-with all the dependencies, I'm  expecting the external files that the app would be looking for to be in the gradle file  
 
### Steps to reproduce
1. setup project in AS 
2.done a build of the project  
3. 

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version:

Device model: 

Stock or customized system:

ownCloud app version:

ownCloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
![image](https://user-images.githubusercontent.com/16129852/35214455-4e68166c-ffb5-11e7-881c-20ba70c4c4b0.png)

![gradle dependencie files screen](https://user-images.githubusercontent.com/16129852/35214429-3a782958-ffb5-11e7-9031-db8913c59721.PNG)

**Comment by davigonz** [comment]
Hi @NZOzzDeveloper , can you check the version of Gradle build tools you have in build.gradle file? Please use 2.3.3 version, have a look at https://github.com/owncloud/android/blob/master/build.gradle#L13

**Comment by davigonz** [comment]
Hi again @NZOzzDeveloper , how have you cloned the repository? Have you used `git clone --recursive https://github.com/owncloud/android.git`

**Comment by NZOzzDeveloper** [comment]
hi Dave 

I cloned the repo. to my then dowloaded the zip file  and created a folder in AS for the project and extracted all the files into named directory.

hmm nope haven't done the clone from console

**Comment by NZOzzDeveloper** [comment]
thanks Dave, thast done the trick

**Comment by davigonz** [comment]
> thanks Dave, thast done the trick

@NZOzzDeveloper Great, if you have any other question while using this project, ping me. Besides, if you want to contribute, there are several issues with `contributions are welcome` label or you can just suggest a new feature 😉
