### ISSUE TITLE
App crashes when using fingerprint lock in Android 8.1

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2182]
### Actual behaviour
- App crashes

### Expected behaviour
- App should ask fingerprint to access
 
### Steps to reproduce
1. Enable passcode lock
2. Introduce passcode
3. Enable fingerprint lock
4. Close the app
5. Open the app
6. ownCloud has stopped message appears

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version: 8.1.0 

Device model: Huawei Nexus 6P

Stock or customized system: Stock

ownCloud app version: 2.7.0 and 2.7.0 beta

ownCloud server version: 10.0.3

#### Android Logcat
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.owncloud.android/com.owncloud.android.ui.activity.FingerprintActivity}: java.security.ProviderException: Keystore operation failed
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                     at android.os.Handler.dispatchMessage(Handler.java:106)
                                                     at android.os.Looper.loop(Looper.java:164)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                  Caused by: java.security.ProviderException: Keystore operation failed
                                                     at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:321)
                                                     at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:604)
                                                     at com.owncloud.android.ui.activity.FingerprintActivity.generateAndStoreKey(FingerprintActivity.java:128)
                                                     at com.owncloud.android.ui.activity.FingerprintActivity.onCreate(FingerprintActivity.java:79)
                                                     at android.app.Activity.performCreate(Activity.java:6999)
                                                     at android.app.Activity.performCreate(Activity.java:6990)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                     at android.os.Looper.loop(Looper.java:164) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
                                                  Caused by: android.security.KeyStoreException: User authentication required
                                                     at android.security.KeyStore.getKeyStoreException(KeyStore.java:672)
                                                     at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:322)
                                                     at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:604) 
                                                     at com.owncloud.android.ui.activity.FingerprintActivity.generateAndStoreKey(FingerprintActivity.java:128) 
                                                     at com.owncloud.android.ui.activity.FingerprintActivity.onCreate(FingerprintActivity.java:79) 
                                                     at android.app.Activity.performCreate(Activity.java:6999) 
                                                     at android.app.Activity.performCreate(Activity.java:6990) 
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                     at android.os.Looper.loop(Looper.java:164) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

**Comment by davigonz** [comment]
It seems to be an Android bug itself, the problem has been fixed after installing **Security patch level: April 1, 2018**, closing...

**Comment by AbithaAntony** [comment]
I am getting same crash in Samsung s7 OS version 8.0.0

**Comment by davigonz** [comment]
> I am getting same crash in Samsung s7, OS version 8.0.0

Hi @AbithaAntony , don't you have any pending updates after 8.0.0? This was fixed with an Android update, at least within Android stock.

**Comment by icyerasor** [comment]
Had the same issue (with another app though and Android Q/10) - try going into the "nexus imprint" / "fingerprint" settings of android OS and changing some stuff there - i.e. display the name of the imprints, change it, etc. For me no re-setup of the imprints was necessary.
Afterwards, back in the app everything worked again..

**Comment by DeepanJN** [comment]
I'm facing the exact same issue with low-end device [ Karbonn Aura Note 4G ] API 23 

javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:174)
Caused by: java.security.ProviderException: Keystore operation failed

Kindly help me!
