### ISSUE TITLE
App cannot open folders with name that contains a space

### ISSUE THREAD

**Issue by cdutsov** [owncloud/android#2253]
### Actual behaviour
-Tell us what happens
When trying to open folder or upload to folders containing space in their name, the app fails to do so. For example opening folder "My Files" will not work, whereas "My-Files" will be opened.

### Expected behaviour
-Tell us what should happen
 The app should open folders containing a space in their name.

### Steps to reproduce
1.Make a folder with space in the name 
2. Try to open it

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version: Lineage OS 15.1 (Oreo)

Device model: Xiaomi Redmi Note 5 Pro

Stock or customized system: Customized

ownCloud app version: version 2.7.0

ownCloud server version: 10.0.9

#### App log

```
07-03 12:43:53.739  4301 12666 E ReadRemoteFolderOperation: Synchronized /Documents/Physics/Krasi/Project Polyrad/: HTTP violation
07-03 12:43:53.739  4301 12666 E ReadRemoteFolderOperation: org.apache.commons.httpclient.URIException: escaped absolute path not valid
07-03 12:43:53.739  4301 12666 E ReadRemoteFolderOperation: 	at org.apache.commons.httpclient.URI.setRawPath(URI.java:2837)
07-03 12:43:53.739  4301 12666 E ReadRemoteFolderOperation: 	at org.apache.commons.httpclient.URI.parseUriReference(URI.java:2023)
07-03 12:43:53.739  4301 12666 E ReadRemoteFolderOperation: 	at org.apache.commons.httpclient.URI.<init>(URI.java:167)
07-03 12:43:53.739  4301 12666 E ReadRemoteFolderOperation: 	at com.owncloud.android.lib.common.OwnCloudClient.followRedirection(OwnCloudClient.java:323)
07-03 12:43:53.739  4301 12666 E ReadRemoteFolderOperation: 	at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:239)
07-03 12:43:53.739  4301 12666 E ReadRemoteFolderOperation: 	at com.owncloud.android.lib.resources.files.ReadRemoteFolderOperation.run(ReadRemoteFolderOperation.java:79)
07-03 12:43:53.739  4301 12666 E ReadRemoteFolderOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.runOperation(RemoteOperation.java:266)
07-03 12:43:53.739  4301 12666 E ReadRemoteFolderOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:142)
07-03 12:43:53.739  4301 12666 E ReadRemoteFolderOperation: 	at com.owncloud.android.operations.SynchronizeFolderOperation.fetchRemoteFolder(SynchronizeFolderOperation.java:253)
07-03 12:43:53.739  4301 12666 E ReadRemoteFolderOperation: 	at com.owncloud.android.operations.SynchronizeFolderOperation.run(SynchronizeFolderOperation.java:206)
07-03 12:43:53.739  4301 12666 E ReadRemoteFolderOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.runOperation(RemoteOperation.java:266)
07-03 12:43:53.739  4301 12666 E ReadRemoteFolderOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:142)
07-03 12:43:53.739  4301 12666 E ReadRemoteFolderOperation: 	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:91)
07-03 12:43:53.739  4301 12666 E ReadRemoteFolderOperation: 	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:143)
07-03 12:43:53.739  4301 12666 E ReadRemoteFolderOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.runOperation(RemoteOperation.java:266)
07-03 12:43:53.739  4301 12666 E ReadRemoteFolderOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:232)
07-03 12:43:53.739  4301 12666 E ReadRemoteFolderOperation: 	at java.lang.Thread.run(Thread.java:764)
07-03 12:43:53.739  4301 12666 E SynchronizeFolderOperation: Checked cdutsov@oc.tdcr.xyz/Documents/Physics/Krasi/Project Polyrad/ : HTTP violation
07-03 12:43:53.739  4301 12666 E SynchronizeFolderOperation: org.apache.commons.httpclient.URIException: escaped absolute path not valid
07-03 12:43:53.739  4301 12666 E SynchronizeFolderOperation: 	at org.apache.commons.httpclient.URI.setRawPath(URI.java:2837)
07-03 12:43:53.739  4301 12666 E SynchronizeFolderOperation: 	at org.apache.commons.httpclient.URI.parseUriReference(URI.java:2023)
07-03 12:43:53.739  4301 12666 E SynchronizeFolderOperation: 	at org.apache.commons.httpclient.URI.<init>(URI.java:167)
07-03 12:43:53.739  4301 12666 E SynchronizeFolderOperation: 	at com.owncloud.android.lib.common.OwnCloudClient.followRedirection(OwnCloudClient.java:323)
07-03 12:43:53.739  4301 12666 E SynchronizeFolderOperation: 	at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:239)
07-03 12:43:53.739  4301 12666 E SynchronizeFolderOperation: 	at com.owncloud.android.lib.resources.files.ReadRemoteFolderOperation.run(ReadRemoteFolderOperation.java:79)
07-03 12:43:53.739  4301 12666 E SynchronizeFolderOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.runOperation(RemoteOperation.java:266)
07-03 12:43:53.739  4301 12666 E SynchronizeFolderOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:142)
07-03 12:43:53.739  4301 12666 E SynchronizeFolderOperation: 	at com.owncloud.android.operations.SynchronizeFolderOperation.fetchRemoteFolder(SynchronizeFolderOperation.java:253)
07-03 12:43:53.739  4301 12666 E SynchronizeFolderOperation: 	at com.owncloud.android.operations.SynchronizeFolderOperation.run(SynchronizeFolderOperation.java:206)
07-03 12:43:53.739  4301 12666 E SynchronizeFolderOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.runOperation(RemoteOperation.java:266)
07-03 12:43:53.739  4301 12666 E SynchronizeFolderOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:142)
07-03 12:43:53.739  4301 12666 E SynchronizeFolderOperation: 	at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:91)
07-03 12:43:53.739  4301 12666 E SynchronizeFolderOperation: 	at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:143)
07-03 12:43:53.739  4301 12666 E SynchronizeFolderOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.runOperation(RemoteOperation.java:266)
07-03 12:43:53.739  4301 12666 E SynchronizeFolderOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:232)
07-03 12:43:53.739  4301 12666 E SynchronizeFolderOperation: 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by kolevv** [comment]
I'm using version 2.8.0 and am unable to reproduce this bug. Running OxygenOS 5.1.4

**Comment by theScrabi** [comment]
This is an error which seem to be related to apache HttpClient. Please wait until the next release, we are about to remove okHttp.

**Comment by jesmrec** [comment]
@cdutsov networking library was replaced and it is available in beta version, if you want to have a look.

**Comment by davigonz** [comment]
@cdutsov is this still reproducible?

**Comment by cdutsov** [comment]
The error seems to be fixed. 
ownCloud Android app version: 2.9.3
ownCloud server version: 10.0.10.4

I think that you can mark this as fixed. :)

**Comment by davigonz** [comment]
Great @cdutsov ! Thanks
