### ISSUE TITLE
Command failed: gradlew.bat installDebug

### ISSUE THREAD

**Issue by wxy1234567890** [owncloud/android#2458]
problems as follows:
FAILURE: Build failed with an exception.

* Where:
Settings file 'F:\myRNproject\android\settings.gradle' line: 3

* What went wrong:
Could not compile settings file 'F:\myRNproject\android\settings.gradle'.
> startup failed:
  settings file 'F:\myRNproject\android\settings.gradle': 3: unexpected char: '\' @ line 3, column 127.
     ules\react-native-vector-icons\android')
                                   ^

  1 error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: gradlew.bat installDebug

Error: Command failed: gradlew.bat installDebug
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:13)
    at runOnAllDevices (F:\myRNproject\node_modules\react-native\local-cli\runAndroid\runAndroid.js:299:19)
    at buildAndRun (F:\myRNproject\node_modules\react-native\local-cli\runAndroid\runAndroid.js:135:12)
    at isPackagerRunning.then.result (F:\myRNproject\node_modules\react-native\local-cli\runAndroid\runAndroid.js:65:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by hannesa2** [comment]
You are in the right repository ? React native ? Javascript ?

![image](https://user-images.githubusercontent.com/3314607/53148015-9c53e600-35a9-11e9-96ef-dab405f87771.png)

This is my `settings.gradle` I've no `@ line 3, column 127`
I guess there is the source (solution?) of your problem
