### ISSUE TITLE
Owncloud application crashes when using FTP, SFTP or WebDav Ext.storage

### ISSUE THREAD

**Issue by braniqvranik** [owncloud/android#2459]
### Actual behaviour
The app was really good until I changed data sources. When setting your OC to use local filesystem (which is not recommended for security reason), this mobile app was perfect. When I've added NGINX webdav or Apache Webdav storage, the application crashes and is unusable. You click on 3-4 dirs and it crashes, my Samsung J7 closes the app. To the developers: Can you please replicate this issue & fix? 

### Expected behaviour
- Application must not crash
 
### Steps to reproduce
1. Setup FTP, SFTP or WebDav External storage
2. Browse it via Web - OK
3. Browse it via OC Mobile application. - NOK
Mobile application crashes.

1. Remove all external storages
2. Enable Local storage inside config/config.php with 'files_external_allow_create_new_local' => 'true', param.
3. Attach external "Local storage"
4. Browse via Web - OK
5. Browse via OC Mobile application
Mobile application no longer crashes.

Can this problem be reproduced with the official owncloud server? No, since Local storage option needs to be added into config.php file.
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version: 8.1.0

Device model: Samsung J7

Stock or customized system:
Stock

ownCloud app version:
ownCloud for Android 2.9.3

ownCloud server version:
ownCloud 10.0.10 (stable) 

#### Web server error log
```
N/A
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"XGCA8tATP2lCDI79zevWSAAAAAk","level":3,"time":"February 10, 2019 19:52:19","remoteAddr":"10.10.10.2","user":"admin","app":"no app in context","method":"GET","url":"\/index.php\/apps\/files_external\/userglobalstorages\/4?testOnly=false","message":"Exception: {\"Exception\":\"Sabre\\\\HTTP\\\\ClientException\",\"Message\":\"Peer's Certificate issuer is not recognized.\",\"Code\":60,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/http\\\/lib\\\/Client.php(103): Sabre\\\\HTTP\\\\Client->doRequest(Object(Sabre\\\\HTTP\\\\Request))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Client.php(231): Sabre\\\\HTTP\\\\Client->send(Object(Sabre\\\\HTTP\\\\Request))\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(259): Sabre\\\\DAV\\\\Client->propFind('https:\\\/\\\/gdisk.b...', Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(579): OC\\\\Files\\\\Storage\\\\DAV->propfind('')\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(440): OC\\\\Files\\\\Storage\\\\DAV->stat('')\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/External\\\/LegacyUtil.php(205): OC\\\\Files\\\\Storage\\\\Common->test(false, false)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(254): OC\\\\Files\\\\External\\\\LegacyUtil::getBackendStatus('\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, false, false)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/UserGlobalStoragesController.php(121): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OC\\\\Files\\\\External\\\\StorageConfig), false)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): OCA\\\\Files_External\\\\Controller\\\\UserGlobalStoragesController->show(4, false)\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\UserGlobalStoragesController), 'show')\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\UserGlobalStoragesController), 'show')\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Files_Exter...', 'show', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(909): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/http\\\/lib\\\/Client.php\",\"Line\":356}"}
```

**Comment by michaelstingl** [comment]
@braniqvranik The request in `owncloud.log` isn't one triggered by the Android app. The `reqId` should have the `X-REQUEST-ID` format. (see https://github.com/owncloud/android/issues/2055)

**Comment by braniqvranik** [comment]
Well, I was not able to find the log showing the issue, maybe the insufficient debug level. Have you tried to simulate this issue on your own ? @michaelstingl

**Comment by michaelstingl** [comment]
> Have you tried to simulate this issue on your own ?

@braniqvranik Not yet. @jesmrec wanted to have a look.

BTW next version of the app will have a debug log that can be enabled by users. (https://github.com/owncloud/android/pull/2439) It will show you the `X-REQUEST-ID` of the error in the app, then you can `grep` for it in the `owncloud.log`.

**Comment by DeepDiver1975** [comment]
🤖 Automated issue triage by Claude Code review agent.

This issue was opened before 2020 and has had no activity since then, so we are
closing it as outdated. If this is still relevant on a current ownCloud release,
please **reopen** (or open a fresh issue) with up-to-date details — thank you\!
