### ISSUE TITLE
[BUG] Copy a folder with subfolders to different accounts doesn't work as expected

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2658]
### Actual behaviour
- Folder, subfolders and containing files are not copied.

### Expected behaviour
- Folder, subfolders and containing files are properly copied.
 
### Steps to reproduce
1. Open Files app or other app supporting the document provider.
2. Select an ownCloud account from the side menu.
3. Long press a folder with subfolders and files inside and press copy to in the three-dots menu.
4. Select a different ownCloud account as destination to copy the files.

### Environment data
Android version: 10

Device model: Pixel 3 XL

Stock or customized system: stock

ownCloud app version: - master

#### ownCloud Android app log
```
2019-09-13 14:46:56.002 8069-9398/com.owncloud.android.debug E/CreateFolderOperation: /Test/ hasn't been created
2019-09-13 14:46:56.004 8069-9398/com.owncloud.android.debug E/DatabaseUtils: Writing exception to parcel
    android.os.ParcelableException: java.io.FileNotFoundException: Remote Operation failed
        at android.provider.DocumentsProvider.call(DocumentsProvider.java:1069)
        at android.content.ContentProvider.call(ContentProvider.java:2152)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:477)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:277)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
     Caused by: java.io.FileNotFoundException: Remote Operation failed
        at com.owncloud.android.providers.DocumentsStorageProvider.checkOperationResult(DocumentsStorageProvider.kt:377)
        at com.owncloud.android.providers.DocumentsStorageProvider.createFolder(DocumentsStorageProvider.kt:393)
        at com.owncloud.android.providers.DocumentsStorageProvider.createDocument(DocumentsStorageProvider.kt:299)
        at android.provider.DocumentsProvider.callUnchecked(DocumentsProvider.java:1121)
        at android.provider.DocumentsProvider.call(DocumentsProvider.java:1067)
        at android.content.ContentProvider.call(ContentProvider.java:2152) 
        at android.content.ContentProvider$Transport.call(ContentProvider.java:477) 
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:277) 
        at android.os.Binder.execTransactInternal(Binder.java:1021) 
        at android.os.Binder.execTransact(Binder.java:994) 
```

**Comment by DeepDiver1975** [comment]
🤖 Automated issue triage by Claude Code review agent.

This issue was opened before 2020 and has had no activity since then, so we are
closing it as outdated. If this is still relevant on a current ownCloud release,
please **reopen** (or open a fresh issue) with up-to-date details — thank you\!

**Comment by jesmrec** [comment]
Still reproducible. Reopening.
