### ISSUE TITLE
[BUG] Move files to a different oC account using the document provider doesn't work as expected

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2659]
### Actual behaviour
- Notification Couldn't move 3 items appears.

### Expected behaviour
- Files are properly moved.
 
### Steps to reproduce
1. Attach two accounts to oC app
2. Open Files/Download app to work with document provider
3. Select several files (i selected three)
4. Move the selected files to the another oC account

### Environment data
Android version: 9

Device model: Xiaomi MI A2

Stock or customized system: Android One

#### ownCloud Android app log

`
2019-09-13 14:19:32.780 29378-30309/? E/CopyJob: Failed to copy content://org.owncloud.documents/document/18 com.android.documentsui.services.ResourceException: Failed to open a file for content://org.owncloud.documents/document/18 due to an exception. at com.android.documentsui.services.CopyJob.copyFileHelper(CopyJob.java:584) at com.android.documentsui.services.CopyJob.byteCopyDocument(CopyJob.java:472) at com.android.documentsui.services.MoveJob.processDocument(MoveJob.java:176) at com.android.documentsui.services.CopyJob.start(CopyJob.java:287) at com.android.documentsui.services.Job.run(Job.java:156) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:764) Caused by: android.os.OperationCanceledException: The operation has been canceled. at android.os.CancellationSignal.throwIfCanceled(CancellationSignal.java:54) at android.content.ContentProviderClient.openFile(ContentProviderClient.java:374) at com.android.documentsui.services.CopyJob.copyFileHelper(CopyJob.java:580) at com.android.documentsui.services.CopyJob.byteCopyDocument(CopyJob.java:472)  at com.android.documentsui.services.MoveJob.processDocument(MoveJob.java:176)  at com.android.documentsui.services.CopyJob.start(CopyJob.java:287)  at com.android.documentsui.services.Job.run(Job.java:156)  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)  at java.util.concurrent.FutureTask.run(FutureTask.java:266)  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)  at java.lang.Thread.run(Thread.java:764)  2019-09-13 14:19:32.788 29378-29378/? E/FileOperationService: Job failed to process docs: [DocumentInfo{docId=17, name=IMG_0001.MOV, mimeType=video/quicktime, isContainer=false, isDirectory=false, isArchive=false, isInArchive=false, isPartial=false, isVirtual=false, isDeleteSupported=true, isCreateSupported=false, isRenameSupported=true, isMetadataSupported=false} @ content://org.owncloud.documents/document/17, DocumentInfo{docId=6, name=RPReplay_Final1568368586.MP4, mimeType=video/mp4, isContainer=false, isDirectory=false, isArchive=false, isInArchive=false, isPartial=false, isVirtual=false, isDeleteSupported=true, isCreateSupported=false, isRenameSupported=true, isMetadataSupported=false} @ content://org.owncloud.documents/document/6, DocumentInfo{docId=18, name=fujifilmyy_xe1_manual_en 2 3.pdf, mimeType=application/pdf, isContainer=false, isDirectory=false, isArchive=false, isInArchive=false, isPartial=false, isVirtual=false, isDeleteSupported=true, isCreateSupported=false, isRenameSupported=true, isMetadataSupported=false} @ content://org.owncloud.documents/document/18].
`

**Comment by DeepDiver1975** [comment]
🤖 Automated issue triage by Claude Code review agent.

This issue was opened before 2020 and has had no activity since then, so we are
closing it as outdated. If this is still relevant on a current ownCloud release,
please **reopen** (or open a fresh issue) with up-to-date details — thank you\!

**Comment by jesmrec** [comment]
Still reproducible. Reopening.
