### ISSUE TITLE
[BUG] Copying/Moving files to ownCloud through document provider does not work if app folders are not created

### ISSUE THREAD

**Issue by davigonz** [owncloud/android#2662]
### Actual behaviour
- Files are not copied/moved to ownCloud.

### Expected behaviour
- Files are properly copied/moved to ownCloud.
 
### Steps to reproduce
1. Remove all the folders related to ownCloud from your internal storage.
2. Install ownCloud app.
3. Open Files/Downloads app.
4. Select a bunch of files
5. Tap three dots button and select copy or move.

### Environment data
Android version: 8.1.0

Device model: Nexus 5X

Stock or customized system: Stock

ownCloud app version: 2.12

#### Android logs
```
2019-09-18 13:40:01.584 24792-24855/com.owncloud.android.debug E/DatabaseUtils: Writing exception to parcel
    android.os.ParcelableException: java.io.FileNotFoundException: File -1 not found
        at android.provider.DocumentsProvider.call(DocumentsProvider.java:951)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:401)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:272)
        at android.os.Binder.execTransact(Binder.java:697)
     Caused by: java.io.FileNotFoundException: File -1 not found
        at com.owncloud.android.providers.DocumentsStorageProvider.getFileByIdOrException(DocumentsStorageProvider.kt:516)
        at com.owncloud.android.providers.DocumentsStorageProvider.deleteDocument(DocumentsStorageProvider.kt:332)
        at android.provider.DocumentsProvider.callUnchecked(DocumentsProvider.java:1046)
        at android.provider.DocumentsProvider.call(DocumentsProvider.java:949)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:401) 
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:272) 
        at android.os.Binder.execTransact(Binder.java:697) 
```

The reason of this problem is that the document providers needs to have a temporal folder in external storage to copy/move files and that folder is not currently created till we download something from the ownCloud app.

**Comment by DeepDiver1975** [comment]
🤖 Automated issue triage by Claude Code review agent.

This issue was opened before 2020 and has had no activity since then, so we are
closing it as outdated. If this is still relevant on a current ownCloud release,
please **reopen** (or open a fresh issue) with up-to-date details — thank you\!

**Comment by jesmrec** [comment]
Still reproducible
