### ISSUE TITLE
Upgrading from old endpoints. Some tests and results.

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2790]
After releasing 2.14 version, let's do some retrospective in the upgrading for app versions with old endpoints, that's it, versions older than 2.9

```
Old endpoint: remote.php/webdav/ <br>
New endpoint: remote.php/dav/files/<user>/
```

Upgrading matrix was totally correct: 

| From..To | 2.9.3 | 2.10 | 2.11 | 2.12 | 2.13 | 2.14 |
| :-------: | :---: | :--: | :--: | :--: | :--: | :--: |
| 2.6 | OK | OK | OK | OK | OK | OK | 
| 2.7 | OK | OK | OK | OK | OK | OK | 
| 2.8 | OK | OK | OK | OK | OK | OK | 

An specific upgrading scenario was reporting here https://github.com/owncloud/android/issues/2787

So, the scenario of upgrading from 2.6 to 2.13.1 was also recorded. The final result is OK. In the video you will see the following steps (using the creation of a folder as operation)

1. In device, 2.6 version is installed (you will see in the User-Agent)
2. Creation of a folder called "Test1" (MKCOL operation), by calling the old dav endpoint, as you can check in the mitmproxy flow.
3. Upgrading to 2.13.1
4. Creation of a folder called "Test2". In this case the endpoint is the new one.

[upgradeFrom2.6.zip](https://github.com/owncloud/android/files/4065793/upgradeFrom2.6.zip)

I noticed one issue:

1. Install an old-endpoint-supported-version (<2.9). No matter the server version.
2. Upgrade to 2.14.1

Current: app crashes, but after restarting it works properly.
Expected: no crash

Time difference between release 2.8 (latest old-endpoint-supported-version) and 2.14.1 is 18 months... so, it will not be a usual case to upgrade from one to the another one. Does it worth to check and fix the issue for the following versions @michaelstingl ?

**Comment by michaelstingl** [comment]
@diocas could you have a look what is different from your tests?

**Comment by michaelstingl** [comment]
> Does it worth to check and fix the issue for the following versions @michaelstingl ?

@jesmrec @davigonz How would you estimate the effort? How often do we see this crash in the Play Store Console?

**Comment by davigonz** [comment]
@jesmrec could you post here (or in a separate issue) the crash logs so I can have a look at it and give an estimation to fix it?

**Comment by diocas** [comment]
The test I had done was to look into the logs as soon as we upgraded for the first time. Now I looked again with a colleague Phone, and he was being redirected to the new endpoints. Maybe there was some redirect on our side being cached.. I don't know, but it seems to be fine now.
Fine, but still not working... but that's another problem with our server. We should deploy the fix next week to test again everything from scratch. 
Sorry for all the trouble and thank you for the help!

**Comment by jesmrec** [comment]
@davigonz for estimation:

```
2020-01-17 11:54:30.640 8982-9027/? E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: com.owncloud.android, PID: 8982
    java.lang.Error: org.koin.core.error.NoBeanDefFoundException: No definition found for 'com.owncloud.android.data.capabilities.datasources.implementation.OCLocalCapabilitiesDataSource' has been found. Check your module definitions.
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1139)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: org.koin.core.error.NoBeanDefFoundException: No definition found for 'com.owncloud.android.data.capabilities.datasources.implementation.OCLocalCapabilitiesDataSource' has been found. Check your module definitions.
        at org.koin.core.scope.Scope.findDefinition(Scope.kt:170)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:164)
        at org.koin.core.scope.Scope.get(Scope.kt:128)
        at com.owncloud.android.providers.FileContentProvider$DataBaseHelper$onUpgrade$$inlined$inject$1.invoke(ComponentCallbackExt.kt:51)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.owncloud.android.providers.FileContentProvider$DataBaseHelper$onUpgrade$1.run(FileContentProvider.kt:1006)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:761) 
2020-01-17 11:54:30.653 923-7729/? W/ActivityManager:   Force finishing activity com.owncloud.android/.ui.activity.SplashActivity
2020-01-17 11:54:30.690 923-3796/? I/ActivityManager: START u0 {cmp=com.owncloud.android/.ui.activity.FileDisplayActivity} from uid 13043 on display 0
2020-01-17 11:54:30.691 923-3796/? W/ActivityManager: startActivity called from finishing ActivityRecord{27dce42 u0 com.owncloud.android/.ui.activity.SplashActivity t4918 f}; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.owncloud.android/.ui.activity.FileDisplayActivity }
2020-01-17 11:54:30.700 923-4433/? W/ActivityManager: Duplicate finish request for ActivityRecord{27dce42 u0 com.owncloud.android/.ui.activity.SplashActivity t4918 f}
2020-01-17 11:54:30.841 8982-8982/? I/art:     at void com.owncloud.android.ui.activity.FileDisplayActivity.onCreate(android.os.Bundle) (FileDisplayActivity.kt:214)
2020-01-17 11:54:30.841 8982-8982/? I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.owncloud.android-2/base.apk"],nativeLibraryDirectories=[/data/app/com.owncloud.android-2/lib/arm64, /system/lib64, /vendor/lib64]]
2020-01-17 11:54:30.841 8982-8982/? I/art:     at void com.owncloud.android.ui.activity.FileDisplayActivity.onCreate(android.os.Bundle) (FileDisplayActivity.kt:214)
2020-01-17 11:54:32.095 923-1040/? I/ActivityManager: Displayed com.owncloud.android/.ui.activity.FileDisplayActivity: +1s368ms (total +1s784ms)
```

**Comment by davigonz** [comment]
> for estimation:

Could you give me more context? Does the error happen when opening the app? Some steps to reproduce?

**Comment by jesmrec** [comment]
yes, you have to perform these steps:

I noticed one issue:

1. Install an old-endpoint-supported-version (<2.9). No matter the server version.
2. Upgrade to 2.14.1

Current: app crashes, but after restarting it works properly.
Expected: no crash

crash happens just after upgrading and opening the app.

**Comment by diocas** [comment]
Hi, we created a client support ticket because we have many users that have a similar problem as the one @jesmrec is reporting.
Many users, after upgrading, say the app keeps crashing (unlike what @jesmrec  says, restarting doesn't solve it). Usually cleaning the cache+storage fixes the problem, but at least one users says that for him it doesn't.  We sent the stack trace in the support ticket but I can paste them here if needed.
