### ISSUE TITLE
[BUG] Reported crash in OCFileListFragment

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2895]
This crash was reported in Google Console

```
java.lang.NullPointerException: 
 
  at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory (OCFileListFragment.java:983)
  at com.owncloud.android.ui.fragment.OCFileListFragment.lambda$listDirectoryWidthAnimationUp$4$OCFileListFragment (OCFileListFragment.java:764)
  at com.owncloud.android.ui.fragment.-$$Lambda$OCFileListFragment$xZj3WyovpoK7b0u2-N-Y6ClHENE.run (lambda)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6682)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)

```

Android version: Mainly in Android 9 and 10

**Comment by selius** [comment]
It looks like I'm affected by this crash.
It happens when I press the Back button on the main screen. It doesn't crash when I switch to another application without pressing Back.
I'm running ownCloud version 2.15.3 on Android 8.

And here's my logcat output that seems to be very similar to the one in the issue description:
```
12-18 14:55:09.350 E/AndroidRuntime( 3774): FATAL EXCEPTION: main
12-18 14:55:09.350 E/AndroidRuntime( 3774): Process: com.owncloud.android, PID: 3774
12-18 14:55:09.350 E/AndroidRuntime( 3774): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
12-18 14:55:09.350 E/AndroidRuntime( 3774): 	at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:107)
12-18 14:55:09.350 E/AndroidRuntime( 3774): 	at com.owncloud.android.ui.fragment.OCFileListFragment.lambda$listDirectoryWidthAnimationUp$4$OCFileListFragment(OCFileListFragment.java:765)
12-18 14:55:09.350 E/AndroidRuntime( 3774): 	at com.owncloud.android.ui.fragment.-$$Lambda$OCFileListFragment$xZj3WyovpoK7b0u2-N-Y6ClHENE.run(Unknown Source:4)
12-18 14:55:09.350 E/AndroidRuntime( 3774): 	at android.os.Handler.handleCallback(Handler.java:789)
12-18 14:55:09.350 E/AndroidRuntime( 3774): 	at android.os.Handler.dispatchMessage(Handler.java:98)
12-18 14:55:09.350 E/AndroidRuntime( 3774): 	at android.os.Looper.loop(Looper.java:180)
12-18 14:55:09.350 E/AndroidRuntime( 3774): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
12-18 14:55:09.350 E/AndroidRuntime( 3774): 	at java.lang.reflect.Method.invoke(Native Method)
12-18 14:55:09.350 E/AndroidRuntime( 3774): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
12-18 14:55:09.350 E/AndroidRuntime( 3774): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:853)
12-18 14:55:09.352 E/ActivityManager( 1526): App crashed! Process: com.owncloud.android
```

I can help with testing, if you want me to build a version from the sources, for example.

**Comment by jesmrec** [comment]
thanks! all info you can send us will be useful. With your steps i was not able to reproduce. Is this something that you reproduce always with the same steps?

**Comment by selius** [comment]
Yes, basically every time I open the app and then press Back, it crashes. I have 16 folders on my main screen, just in case it's something related to the number of objects in the list.

**Comment by selius** [comment]
Okay, I checked out the latest revision from master and ran under the debugger and I think I found out what the problem was.

In `FileDisplayActivity.onBackPressed`:
```kotlin
            // all closed
            val listOfFiles = listOfFilesFragment
            if (secondFragment == null) {
                val currentDir = currentDir
                if (currentDir == null || currentDir.parentId == FileDataStorageManager.ROOT_PARENT_ID.toLong()) {
                    finish()
                }
                listOfFiles?.onBrowseUp()
            }
```
the root directory is correctly detected and `finish()` is called on the activity, but right after that `listOfFiles?.onBrowseUp()` is called, which in turn calls `OCFileListFragment.listDirectoryWidthAnimationUp` that attempts to run some animation using `postDelayed`:
```java
            // This is a ugly hack for getting rid of the "ArrayOutOfBound" exception we get when we
            // call listDirectory() from the Animation callback
            eventHandler.postDelayed(() -> {
                listDirectory(file);
                Animation fadeInFront = AnimationUtils.loadAnimation(getContext(), R.anim.dir_fadein_front);
                getListView().startAnimation(fadeInFront);
            }, getResources().getInteger(R.integer.folder_animation_duration));
            getListView().startAnimation(fadeOutBack);
```
By the moment the queue gets to executing this, the activity and context is already destroyed, and so the crash happens.

I don't think `listOfFiles?.onBrowseUp()` should be called after calling `finish()`, so the fix could be to just return from the `onBackPressed` function right after calling `finish()`.

**Comment by jesmrec** [comment]
CC @abelgardep

**Comment by abelgardep** [comment]
@selius Thank you for that research! Yes, i think you are right! I can update it, but since it is your contribution, would you like to send a PR?

**Comment by selius** [comment]
Sure, here you go - #3042. Thanks!

**Comment by abelgardep** [comment]
No reports for this crash in 2.16. Thanks a lot for the fix!  @selius
