### ISSUE TITLE
[BUG] Av. offline from scratch

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#2953]
From time to time, i've detected the following error:

```
2020-09-09 17:14:04.648 24091-24091/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.owncloud.android, PID: 24091
    android.app.RemoteServiceException: Bad notification for startForeground
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Steps:

1. Install from scratch
2. Set a file to available offline

Current: app crashes
Expected: available offline

Android 9

Related PR: https://github.com/owncloud/android/pull/2967

**Comment by abelgardep** [comment]
We should take care of this problem as soon as possible. It is important to fix the problem with notifications in download and upload services.

**Comment by theScrabi** [comment]
Could you please link the PR in the first commend of the issue this way one does not have to scroll to the bottom to find the actual code.
