### ISSUE TITLE
Migration OAuth2 - OIDC

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3000]
Problem comes from https://github.com/owncloud/openidconnect/issues/66#issuecomment-709999406, in the scope of the OAuth2 - OIDC migration. These are the steps (let me know if you need an environment):

1. Connect the app to an OAuth2 server (everything goes fine)
2. Server changes the authentication method from OAuth2 to OIDC
3. OAuth2 is no longer available, so next request returns 401
4. OAuth2 token endpoint is called to get authorization, but this is not longer available either. It returns 302, pointing to the same server's URL + `\login`

Then app crashes:

```
2020-10-20 18:44:51.382 25157-25177/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.owncloud.android, PID: 25157
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:415)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
        at net.openid.appauth.Utils.readInputStream(Utils.java:36)
        at net.openid.appauth.AuthorizationService$TokenRequestTask.doInBackground(AuthorizationService.java:453)
        at net.openid.appauth.AuthorizationService$TokenRequestTask.doInBackground(AuthorizationService.java:395)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 

```

app keeps crashing every time is opened. you can cheat by enabling again OAuth2. 

Expected behaviour: When OAuth2 token expires, `.well-known/openid-configuration` must be checked to know if OIDC is available. In case it is, let user know that he/she must re-authenticate, pointing to the login view and there, authenticate again against OIDC. 

CC @abelgardep @theScrabi

Device: Pixel2 Android 11
Server:

```{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"10.5.0.10","versionstring":"10.5.0","edition":"Community","productname":"ownCloud"}```

OAuth2 v0.4.4
OpenIdConnect 1.0.0RC5

**Comment by michaelstingl** [comment]
@jesmrec could you get me the `mitmproxy` flow of this?

**Comment by jesmrec** [comment]
Flow in Android is not too descriptive

The request to renew the token

```POST …-qa.owncloud.works /index.php/apps/oauth2/api/v1/token``` 

returns 302, and app directly crashes. 

Request is the regular one, and response include headers:

```
Cache-Control:                  no-store, no-cache, must-revalidate                                                                                                                                                                                 
Content-Length:                 0                                                                                                                                                                                                                   
Content-Security-Policy:        default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *                                        
Content-Type:                   text/html; charset=UTF-8                                                                                                                                                                                            
Date:                           Wed, 21 Oct 2020 06:44:23 GMT                                                                                                                                                                                       
Expires:                        Thu, 19 Nov 1981 08:52:00 GMT                                                                                                                                                                                       
Location:                       https://...qa.owncloud.works/login                                                                                                                                                          
Pragma:                         no-cache                                                                                                                                                                                                            
Server:                         Caddy                                                                                                                                                                                                               
Server:                         Apache                                                                                                                                                                                                              
Set-Cookie:                     ocmamgra3prm=4qsggmolmkfq2bbe3vguj0ikrc; path=/; secure; HttpOnly                                                                                                                                                   
Set-Cookie:                     oc_sessionPassphrase=cr8nwO14Mh2W%2FmlmLfCHZsDqCAsm%2FHisd3UEmn308INcyQe%2F2ZMnai6RdIsU4ZUyaHcSJdYSClGCZbOlXtkRQYCEhsOla4aUzpHNix5Vhqer5iUSIEjwpRoQKGcYXyYZ; path=/; secure; HttpOnly; SameSite=strict              
X-Content-Type-Options:         nosniff                                                                                                                                                                                                             
X-Download-Options:             noopen                                                                                                                                                                                                              
X-Frame-Options:                SAMEORIGIN                                                                                                                                                                                                          
X-Permitted-Cross-Domain-Polic  none                                                                                                                                                                                                                
ies:                                                                                                                                                                                                                                                
X-Robots-Tag:                   none                                                                                                                                                                                                                
X-Xss-Protection:               1; mode=block                                                                                                              
```

in iOS:

```
  08:58:47 HTTPS POST ….qa.owncloud.works /index.php/apps/oauth2/api/v1/token   302           [no content]       319ms 
  08:58:47 HTTPS POST ….qa.owncloud.works /login 200              text/html 2.12k 403ms 
  08:58:48 HTTPS GET  ….qa.owncloud.works /status.php  200       application/json  155b 243ms 
  08:58:48 HTTPS GET  ….qa.owncloud.works /.well-known/openid-configuration  302           [no content]       453ms 
  08:58:48 HTTPS GET  ….qa.owncloud.works /remote.php/dav/files   401        application/xml  557b 307ms
  08:58:49 HTTPS GET  ….qa.owncloud.works /remote.php/dav/files 401        application/xml  557b 300ms
```

redirection is followed. At this point, user is asked to re-authenticate and flow starts again.

Let me know if any of you need more info.

**Comment by abelgardep** [comment]
I have performed a quick test just to check what's happening.

It also crashes when you are logged into a OAuth2 server and then you disable oauth2. https://github.com/owncloud/android/issues/2891

Since last release of AppAuth, some PR were merged and i have checked if it still crashes with current master branch. It does not crash. In https://github.com/owncloud/android/pull/3022 we plan to use an AppAuth fork with latest changes. 

We will need to test again with that version.

**Comment by jesmrec** [comment]
After replacing AppAuth with the custom implementation, this crash does not happen anymore. The way in which the migration has to be alligned with other clients will be handled in a separate (common) issue. With the crash fixed, this one is ready to close
