### ISSUE TITLE
[BUG] External app option "Share with" does not share all the selected files

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3055]
### Steps to reproduce

1. Open an external app like "Photos", "Gallery" or another one that stores files
2. Select 20 - 30 files and share them with ownCloud (no matter the account and location)

### Actual behaviour

Not all files are saved. I tested with different amount of files. The bigger the amount of files, the most files are lost.

5 files -> all of them are uploaded
10 files -> 8 uploaded
20 files -> 17 uploaded
40 files -> 21 uploaded
100 files -> 24 uploaded

this numbers changes every try, only an approach.

### Expected behaviour

Everything correctly shared, uploaded and synced

Tested with:

Google Pixel, Android 11
Nexus 6P, Android 7
Server 10.6

**Comment by abelgardep** [comment]
It seems that it is a permission issue, and it was described here:
 https://github.com/owncloud/android/blob/7e276f344e0a41fd9547889976e39ed064c5dd99/owncloudApp/src/main/java/com/owncloud/android/ui/asynctasks/CopyAndUploadContentUrisTask.java#L65-L70
Error:
```
E/(CopyAndUploadContentUrisTask.java:184) .doInBackground(): Not enough permissions to read source file content://com.google.android.apps.nbu.files.provider/2/25240
    java.lang.SecurityException: Permission Denial: reading com.google.android.libraries.storage.storagelib.FileProvider uri content://com.google.android.apps.nbu.files.provider/2/25240 from pid=30110, uid=10944 requires the provider be exported, or grantUriPermission()
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
        at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:781)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1983)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1798)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1475)
        at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:146)
        at com.owncloud.android.ui.asynctasks.CopyAndUploadContentUrisTask.doInBackground(CopyAndUploadContentUrisTask.java:47)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

I need to research a little bit about how we can fix it.

**Comment by jesmrec** [comment]
Thanks!!
