### ISSUE TITLE
[BUG] Error downloading images

### ISSUE THREAD

**Issue by davcres** [owncloud/android#3647]
### Actual behaviour
-Sometimes when you try to open or send and image which is not downloaded, the download fails and the logcat shows two exceptions.

### Expected behaviour
-Download image and send or open it.
 
The problem looks like is more likely when you have the images downloaded and then you remove them and try to download them again.
### Steps to reproduce
1. Download all photos of a folder
2. Remove all photos (local only)
3. Select one of them
4. Try to send it from file list

https://user-images.githubusercontent.com/78238260/165915975-32d666bc-2cd3-4b02-8fce-1d341d97d281.mp4

### Environment data
Android version: Android 11

Device model: Samsung A51

I tried it in the demo server

### Logs
```E/(RemoteOperationResult.java:119) .<init>(): ---------------------------------
    Create RemoteOperationResult from exception.
     Message: IOException: unexpected end of stream on ...
     Stacktrace: java.io.IOException: unexpected end of stream on...
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:54)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at com.owncloud.android.lib.common.http.LogInterceptor.intercept(LogInterceptor.kt:49)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
        at com.owncloud.android.lib.common.http.methods.nonwebdav.HttpMethod.onExecute(HttpMethod.kt:44)
        at com.owncloud.android.lib.common.http.methods.nonwebdav.GetMethod.onExecute(GetMethod.kt:41)
        at com.owncloud.android.lib.common.http.methods.HttpBaseMethod.execute(HttpBaseMethod.kt:75)
        at com.owncloud.android.lib.common.OwnCloudClient.saveExecuteHttpMethod(OwnCloudClient.java:138)
        at com.owncloud.android.lib.common.OwnCloudClient.executeHttpMethod(OwnCloudClient.java:108)
        at com.owncloud.android.lib.resources.files.DownloadRemoteFileOperation.downloadFile(DownloadRemoteFileOperation.java:105)
        at com.owncloud.android.lib.resources.files.DownloadRemoteFileOperation.run(DownloadRemoteFileOperation.java:82)
        at com.owncloud.android.lib.common.operations.RemoteOperation.runOperation(RemoteOperation.java:264)
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:229)
        at com.owncloud.android.operations.DownloadFileOperation.run(DownloadFileOperation.java:153)
        at com.owncloud.android.lib.common.operations.RemoteOperation.runOperation(RemoteOperation.java:264)
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:229)
        at com.owncloud.android.files.services.FileDownloader.downloadFile(FileDownloader.java:442)
        at com.owncloud.android.files.services.FileDownloader.access$400(FileDownloader.java:73)
        at com.owncloud.android.files.services.FileDownloader$ServiceHandler.handleMessage(FileDownloader.java:390)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.io.EOFException: \n not found: limit=0 content=…
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:332)
        at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106) 
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) 
        at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:54) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) 
        at com.owncloud.android.lib.common.http.LogInterceptor.intercept(LogInterceptor.kt:49) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) 
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) 
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) 
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) 
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) 
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197) 
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148) 
        at com.owncloud.android.lib.common.http.methods.nonwebdav.HttpMethod.onExecute(HttpMethod.kt:44) 
        at com.owncloud.android.lib.common.http.methods.nonwebdav.GetMethod.onExecute(GetMethod.kt:41) 
        at com.owncloud.android.lib.common.http.methods.HttpBaseMethod.execute(HttpBaseMethod.kt:75) 
        at com.owncloud.android.lib.common.OwnCloudClient.saveExecuteHttpMethod(OwnCloudClient.java:138) 
        at com.owncloud.android.lib.common.OwnCloudClient.executeHttpMethod(OwnCloudClient.java:108) 
        at com.owncloud.android.lib.resources.files.DownloadRemoteFileOperation.downloadFile(DownloadRemoteFileOperation.java:105) 
        at com.owncloud.android.lib.resources.files.DownloadRemoteFileOperation.run(DownloadRemoteFileOperation.java:82) 
        at com.owncloud.android.lib.common.operations.RemoteOperation.runOperation(RemoteOperation.java:264) 
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:229) 
        at com.owncloud.android.operations.DownloadFileOperation.run(DownloadFileOperation.java:153) 
        at com.owncloud.android.lib.common.operations.RemoteOperation.runOperation(RemoteOperation.java:264) 
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:229) 
        at com.owncloud.android.files.services.FileDownloader.downloadFile(FileDownloader.java:442) 
        at com.owncloud.android.files.services.FileDownloader.access$400(FileDownloader.java:73) 
        at com.owncloud.android.files.services.FileDownloader$ServiceHandler.handleMessage(FileDownloader.java:390) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
    
    ---------------------------------
E/(DownloadRemoteFileOperation.java:87) .run(): Download of /Photos/Teotihuacan.jpg to /data/user/0/com.owncloud.android.debug/files/owncloud/tmp/admin@135.181.149.201%3A10000/Photos/Teotihuacan.jpg: Unrecovered transport exception
    java.io.IOException: unexpected end of stream on ...
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:54)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at com.owncloud.android.lib.common.http.LogInterceptor.intercept(LogInterceptor.kt:49)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
        at com.owncloud.android.lib.common.http.methods.nonwebdav.HttpMethod.onExecute(HttpMethod.kt:44)
        at com.owncloud.android.lib.common.http.methods.nonwebdav.GetMethod.onExecute(GetMethod.kt:41)
        at com.owncloud.android.lib.common.http.methods.HttpBaseMethod.execute(HttpBaseMethod.kt:75)
        at com.owncloud.android.lib.common.OwnCloudClient.saveExecuteHttpMethod(OwnCloudClient.java:138)
        at com.owncloud.android.lib.common.OwnCloudClient.executeHttpMethod(OwnCloudClient.java:108)
        at com.owncloud.android.lib.resources.files.DownloadRemoteFileOperation.downloadFile(DownloadRemoteFileOperation.java:105)
        at com.owncloud.android.lib.resources.files.DownloadRemoteFileOperation.run(DownloadRemoteFileOperation.java:82)
        at com.owncloud.android.lib.common.operations.RemoteOperation.runOperation(RemoteOperation.java:264)
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:229)
        at com.owncloud.android.operations.DownloadFileOperation.run(DownloadFileOperation.java:153)
        at com.owncloud.android.lib.common.operations.RemoteOperation.runOperation(RemoteOperation.java:264)
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:229)
        at com.owncloud.android.files.services.FileDownloader.downloadFile(FileDownloader.java:442)
        at com.owncloud.android.files.services.FileDownloader.access$400(FileDownloader.java:73)
        at com.owncloud.android.files.services.FileDownloader$ServiceHandler.handleMessage(FileDownloader.java:390)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.io.EOFException: \n not found: limit=0 content=…
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:332)
        at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106) 
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) 
        at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:54) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) 
        at com.owncloud.android.lib.common.http.LogInterceptor.intercept(LogInterceptor.kt:49) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) 
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) 
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) 
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) 
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) 
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197) 
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148) 
        at com.owncloud.android.lib.common.http.methods.nonwebdav.HttpMethod.onExecute(HttpMethod.kt:44) 
        at com.owncloud.android.lib.common.http.methods.nonwebdav.GetMethod.onExecute(GetMethod.kt:41) 
        at com.owncloud.android.lib.common.http.methods.HttpBaseMethod.execute(HttpBaseMethod.kt:75) 
        at com.owncloud.android.lib.common.OwnCloudClient.saveExecuteHttpMethod(OwnCloudClient.java:138) 
        at com.owncloud.android.lib.common.OwnCloudClient.executeHttpMethod(OwnCloudClient.java:108) 
        at com.owncloud.android.lib.resources.files.DownloadRemoteFileOperation.downloadFile(DownloadRemoteFileOperation.java:105) 
        at com.owncloud.android.lib.resources.files.DownloadRemoteFileOperation.run(DownloadRemoteFileOperation.java:82) 
        at com.owncloud.android.lib.common.operations.RemoteOperation.runOperation(RemoteOperation.java:264) 
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:229) 
        at com.owncloud.android.operations.DownloadFileOperation.run(DownloadFileOperation.java:153) 
        at com.owncloud.android.lib.common.operations.RemoteOperation.runOperation(RemoteOperation.java:264) 
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:229) 
        at com.owncloud.android.files.services.FileDownloader.downloadFile(FileDownloader.java:442) 
        at com.owncloud.android.files.services.FileDownloader.access$400(FileDownloader.java:73) 
        at com.owncloud.android.files.services.FileDownloader$ServiceHandler.handleMessage(FileDownloader.java:390) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by jesmrec** [comment]
Checked with `release` variant to assure `stetho` is involved or not. Issue is still reproducible.
