### ISSUE TITLE
[BUG] App crashes at file deletion

### ISSUE THREAD

**Issue by machabeuszan** [owncloud/android#3726]
### Actual behaviour
 - Android app crashes when deleting an image from the full screen view

### Expected behaviour
- After deletion, app should show next image from the list
 
### Steps to reproduce
1. Open Nextcloud app on android
2. Navigate to the directory that contains ~10GB of images and videos (typical 50kB, max 40MB objects)
3. Open one of the images
4. On right top corner, tap "kebab menu"
5. Select "Remove"
6. Confirm to remove
7. Wait until operation finishes
8. Application crashes with Exception as below

Can this problem be reproduced with the official owncloud server?
Not possible to test with personal data with test server

### Cause of error
```java
Exception in thread "main" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.services.OperationsService$OperationsServiceBinder.isSynchronizing(OperationsService.java:372)
    at com.owncloud.android.files.FileMenuFilter.anyFileSynchronizing(FileMenuFilter.java:497)
    at com.owncloud.android.files.FileMenuFilter.anyFileSynchronizing(FileMenuFilter.java:486)
    at com.owncloud.android.files.FileMenuFilter.filter(FileMenuFilter.java:194)
    at com.owncloud.android.files.FileMenuFilter.filter(FileMenuFilter.java:126)
    at com.owncloud.android.ui.preview.PreviewImageFragment.onPrepareOptionsMenu(PreviewImageFragment.java:381)
    at androidx.fragment.app.Fragment.performPrepareOptionsMenu(Fragment.java:3253)
    at androidx.fragment.app.FragmentManager.dispatchPrepareOptionsMenu(FragmentManager.java:3051)
    at androidx.fragment.app.FragmentManager$2.onPrepareMenu(FragmentManager.java:466)
    at androidx.core.view.MenuHostHelper.onPrepareMenu(MenuHostHelper.java:63)
    at androidx.activity.ComponentActivity.onPrepareOptionsMenu(ComponentActivity.java:497)
    at android.app.Activity.onPreparePanel(Activity.java:4364)
    at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
    at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3148)
    at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:1936)
    at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:2190)
    at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:273)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
    at android.view.Choreographer.doCallbacks(Choreographer.java:866)
    at android.view.Choreographer.doFrame(Choreographer.java:792)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8663)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30210090`
* Build flavor: `gplay`

### Device information
* Brand: `samsung`
* Device: `m52xq`
* Model: `SM-M526BR`
* Id: `SP1A.210812.016`
* Product: `m52xqeea`

### Firmware
* SDK: `31`
* Release: `12`
* Incremental: `M526BRXXU1BVD4`

**Comment by jesmrec** [comment]
```
Steps to reproduce
Open Nextcloud app on android
```

```
App information
ID: com.nextcloud.client
Version: 30210090
```

you should report here -> https://github.com/nextcloud/android/issues
