### ISSUE TITLE
[BUG] Upgrade from version before Scoped Storage to new arch causes a crash

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3741]
1. Install 2.18 (before scoped storage)
2. Add an account and upload something (FAB). Wait till uploads finish
3. Update to current

Current: app crashes

```
    Process: com.owncloud.android, PID: 21890
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.owncloud.android/com.owncloud.android.presentation.ui.migration.StorageMigrationActivity}: org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'com.owncloud.android.presentation.viewmodels.migration.MigrationViewModel']
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4035)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

NOTE: same if upload status is "in progress" or "failed"

Expected: migration and finished stuff in uploads view after.

Samsung A51 Android 12
`73cb9054`

**Comment by jesmrec** [comment]
Also reproducible upgrading from 2.18.3

Same stacktrace, i guess:

```
2022-09-05 08:45:05.939 5592-5592/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.owncloud.android, PID: 5592
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.owncloud.android/com.owncloud.android.presentation.ui.migration.StorageMigrationActivity}: org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'com.owncloud.android.presentation.viewmodels.migration.MigrationViewModel']
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4035)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
     Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'com.owncloud.android.presentation.viewmodels.migration.MigrationViewModel']
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
        at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:255)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:242)
        at org.koin.core.scope.Scope.get(Scope.kt:205)
        at org.koin.androidx.viewmodel.factory.DefaultViewModelFactory.create(DefaultViewModelFactory.kt:13)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:171)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:139)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:44)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:31)
        at com.owncloud.android.presentation.ui.migration.StorageMigrationActivity.getMigrationViewModel(StorageMigrationActivity.kt:39)
        at com.owncloud.android.presentation.ui.migration.StorageMigrationActivity.onCreate(StorageMigrationActivity.kt:50)
        at android.app.Activity.performCreate(Activity.java:8290)
        at android.app.Activity.performCreate(Activity.java:8270)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.app.ActivityThread.main(ActivityThread.java:8663) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
     Caused by: org.koin.core.error.NoBeanDefFoundException: |- No definition found for class:'com.owncloud.android.domain.transfers.usecases.GetAllTransfersUseCase'. Check your definitions!
        at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:305)
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:275)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:242)
        at org.koin.core.scope.Scope.get(Scope.kt:205)
        at com.owncloud.android.dependecyinjection.ViewModelModuleKt$viewModelModule$1$16.invoke(ViewModelModule.kt:99)
        at com.owncloud.android.dependecyinjection.ViewModelModuleKt$viewModelModule$1$16.invoke(ViewModelModule.kt:83)
```

Samsung A51 Android 12
`2433f64f7`

**Comment by jesmrec** [comment]
Last message's commit was wrong, so, test repeated with the newest one in `new_arch/synchronization` branch: `8c924755`

Crash happens if the upgrade is not "empty". I mean, after attaching an account and upgrading without uploads, downloads, available offline... this case skips the Scoped Storage migration wizard and works fine.

If the account contains any downloaded/av. offline file or uploads, it crashes with the upper trace.

**Comment by jesmrec** [comment]
Checked again with the finally correct branch, commit `ec4f1b89a`

Unfortunately, it's still crashing. Migration starts but it does not end correctly. I performed basic migration in the following manner:

1. Install 2.18.3 and add account (release apk)
2. Download one file
3. Upgrade to current, running the ScSt migration wizard. (release apk)

Current: crashes during migration, and downloaded file is gone (not downloaded). Here you have the stack trace. It seems that the table is missing somehow:

```
2022-09-05 12:58:59.478 8436-8498/? E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-4
    Process: com.owncloud.android, PID: 8436
    android.database.sqlite.SQLiteException: no such table: filelist (code 1 SQLITE_ERROR[1]): , while compiling: SELECT parent, shared_via_users, created, remote_id, file_owner, is_downloading, update_thumbnail, private_link, path, last_sync_date, modified_at_last_sync_for_data, filename, keep_in_sync, content_type, permissions, etag_in_conflict, last_sync_date_for_data, tree_etag, modified, etag, _id, media_path, content_length, share_by_link FROM filelist WHERE (file_owner = ? ) ORDER BY path ASC 
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1478)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:916)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteDatabase.validateSql(SQLiteDatabase.java:2487)
        at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:573)
        at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:463)
        at com.owncloud.android.providers.FileContentProvider.query(FileContentProvider.kt:407)
        at android.content.ContentProvider.query(ContentProvider.java:1520)
        at android.content.ContentProvider.query(ContentProvider.java:1616)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:286)
        at android.content.ContentResolver.query(ContentResolver.java:1226)
        at android.content.ContentResolver.query(ContentResolver.java:1158)
        at android.content.ContentResolver.query(ContentResolver.java:1114)
        at com.owncloud.android.datamodel.FileDataStorageManager.performQuery(FileDataStorageManager.kt:760)
        at com.owncloud.android.datamodel.FileDataStorageManager.performQuery$default(FileDataStorageManager.kt:748)
        at com.owncloud.android.datamodel.FileDataStorageManager.migrateLegacyToScopedPath(FileDataStorageManager.kt:398)
        at com.owncloud.android.presentation.viewmodels.migration.MigrationViewModel.updateAlreadyDownloadedFilesPath(MigrationViewModel.kt:109)
        at com.owncloud.android.presentation.viewmodels.migration.MigrationViewModel.access$updateAlreadyDownloadedFilesPath(MigrationViewModel.kt:48)
        at com.owncloud.android.presentation.viewmodels.migration.MigrationViewModel$moveLegacyStorageToScopedStorage$1.invokeSuspend(MigrationViewModel.kt:77)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@19d9c9f, Dispatchers.IO]
```

**Comment by jesmrec** [comment]
This one is maybe reproducible from the first version of ScSt, so i let you decide if it's worthy to fix it or not at this point:

1. Install 2.18.3
2. Download something, so that the wizard is triggered afterwards
3. Upgrade to current -> file list shown and so on
4. Press device's back button

Current: Migration wizard displayed again
Expected: Migration wizard finished, therefore no more migrations to do

just in case a quick fix could helo to get rid the problem. If getting complicated, i'd skip it

**Comment by JuancaG05** [comment]
Merged in `new_arch/synchronization`. Everything reported was fixed except for the last comment, which I don't consider is worth fixing as it's been a year since this was released.
