### ISSUE TITLE
[BUG] Crash by set as unav. offline in the av. offline shortcut

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#3976]
### Steps to reproduce

1.  In any account (no matter oCIS, oC10, spaces...), set some files and folders as av. offline
2. Open av. offline shortcut on the bottom bar
3. Select all available offline items there
4. Three-dot-button and `Unset as available offline`

### Actual behaviour

App crashes. Stacktrace:

```
2023-03-20 12:55:42.488 19365-19365/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.owncloud.android.debug, PID: 19365
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.owncloud.android.presentation.files.filelist.FileListAdapter.getCheckedItems(FileListAdapter.kt:157)
        at com.owncloud.android.presentation.files.filelist.MainFileListFragment$actionModeCallback$1.onPrepareActionMode(MainFileListFragment.kt:709)
        at androidx.appcompat.app.AppCompatDelegateImpl$ActionModeCallbackWrapperV9.onPrepareActionMode(AppCompatDelegateImpl.java:2713)
        at androidx.appcompat.view.StandaloneActionMode.invalidate(StandaloneActionMode.java:100)
        at com.owncloud.android.presentation.files.filelist.MainFileListFragment$subscribeToViewModels$3.invokeSuspend(MainFileListFragment.kt:275)
        at com.owncloud.android.presentation.files.filelist.MainFileListFragment$subscribeToViewModels$3.invoke(Unknown Source:8)
        at com.owncloud.android.presentation.files.filelist.MainFileListFragment$subscribeToViewModels$3.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt:214)
        at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Unknown Source:13)
        at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Unknown Source:4)
        at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:34)
        at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:8)
        at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Unknown Source:4)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:33)
        at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:398)
        at kotlinx.coroutines.flow.StateFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:245)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:513)
        at kotlinx.coroutines.channels.AbstractChannel$ReceiveElement.completeResumeReceive(AbstractChannel.kt:908)
        at kotlinx.coroutines.channels.ArrayChannel.offerInternal(ArrayChannel.kt:83)
        at kotlinx.coroutines.channels.AbstractSendChannel.send(AbstractChannel.kt:134)
        at kotlinx.coroutines.channels.ChannelCoroutine.send(Unknown Source:2)
        at kotlinx.coroutines.flow.internal.SendingCollector.emit(SendingCollector.kt:19)
        at com.owncloud.android.presentation.files.filelist.MainFileListViewModel$toFileListUiState$$inlined$map$1$2.emit(Emitters.kt:223)
        at com.owncloud.android.data.files.datasources.implementation.OCLocalFileDataSource$getFilesWithSyncInfoAvailableOfflineFromAccountAsFlow$$inlined$map$1$2.emit(Emitters.kt:223)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:87)
```

### Expected behaviour
No crash.

NOTE: sometimes, i've reproduced it by removing part of the list, not the whole list. F.ex, if there are files and folders in the shortcut, by setting as unav. offline only the files 

Samsung A51, Android12
`oc-android-4.0-beta.1`

**Comment by abelgardep** [comment]
Reproducible in master after merging this? https://github.com/owncloud/android/pull/3974
