### ISSUE TITLE
invoked 'android.accounts.Account com.owncloud.android.lib.common.OwnCloudAccount.getSavedAccount()' on a null object reference

### ISSUE THREAD

**Issue by cs8898** [owncloud/android#4049]
I thought i just have used the Sample code, but it seems that there are some issues...

Because i'm trying to get some ics files from the server i needed some webdav client but `sardine-android` isn't working... "Only WebDAV Client allowed" ;/

So i tried that lib included as
`com.github.owncloud:android-library:oc-android-library-0.9.24`

The used Code:
```java
        Uri serverUri = Uri.parse("https://SOMESERVER.TLD/owncloud/");
        OwnCloudClient mClient = OwnCloudClientFactory.createOwnCloudClient(serverUri, context, true);
        OwnCloudCredentials creds = OwnCloudCredentialsFactory.newBasicCredentials("USERNAME","PASSWORD");
        mClient.setCredentials(creds);
        try {
            ReadRemoteFolderOperation readFolder = new ReadRemoteFolderOperation("/");
            RemoteOperationResult<ArrayList<RemoteFile>> readResponse = readFolder.execute(mClient);
            Log.d("WEBDav",readResponse.getLogMessage());
            if(readResponse.getData() != null)
            for(RemoteFile file : readResponse.getData()){
                Log.d("RemoteFile",file.getRemotePath());
            }
...
```

Heyo here is my Log:
```
Synchronized /: Unexpected exception
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.accounts.Account com.owncloud.android.lib.common.OwnCloudAccount.getSavedAccount()' on a null object reference
        at com.owncloud.android.lib.common.OwnCloudClient.getUserFilesWebDavUri(OwnCloudClient.java:263)
        at com.owncloud.android.lib.resources.files.ReadRemoteFolderOperation.run(ReadRemoteFolderOperation.java:79)
        at com.owncloud.android.lib.common.operations.RemoteOperation.runOperation(RemoteOperation.java:252)
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:215)
```

**Comment by DeepDiver1975** [comment]
🤖 Automated issue triage by Claude Code review agent.

This issue was opened before 2020 and has had no activity since then, so we are
closing it as outdated. If this is still relevant on a current ownCloud release,
please **reopen** (or open a fresh issue) with up-to-date details — thank you\!
