### ISSUE TITLE
[BUG] Downloading file

### ISSUE THREAD

**Issue by segln** [owncloud/android#4057]
### Actual behaviour
Downloading file failed unexpectably

### Expected behaviour
File downloaded
 
### Steps to reproduce
1. Select file
2. Click `Download` button

### Environment data
Android version:
13
Device model: 
SM-A528N
Stock or customized system:

ownCloud app version:
ownCloudrelease 4.0 (26ccad5af)
ownCloud server version:
ocis Version: 2.0.0
Compiled: 2023-06-05 00:00:00 +0000 UTC

#### Web server error log
```
Jun 05 18:44:39 odroid-m1 ocis[465192]: {"level":"warn","service":"frontend","pkg":"rhttp","traceid":"00000000000000000000000000000000","time":"2023-06-05T18:44:39.152882503+09:00","message":"core access token not set"}
Jun 05 18:45:57 odroid-m1 ocis[465192]: {"level":"warn","service":"frontend","pkg":"rhttp","traceid":"00000000000000000000000000000000","time":"2023-06-05T18:45:57.272027843+09:00","message":"core access token not set"}
Jun 05 18:46:29 odroid-m1 ocis[465192]: {"level":"warn","service":"frontend","pkg":"rhttp","traceid":"00000000000000000000000000000000","time":"2023-06-05T18:46:29.015873845+09:00","message":"core access token not set"}
Jun 05 18:46:29 odroid-m1 ocis[465192]: {"level":"warn","service":"frontend","pkg":"rhttp","traceid":"00000000000000000000000000000000","time":"2023-06-05T18:46:29.225668336+09:00","message":"core access token not set"}
Jun 05 18:47:09 odroid-m1 ocis[465192]: {"level":"warn","service":"frontend","pkg":"rhttp","traceid":"00000000000000000000000000000000","time":"2023-06-05T18:47:09.407889947+09:00","message":"core access token not set"}

```

#### ownCloud log (data/owncloud.log)
```
V: 2023-06-05 18:45:55:922(MainApp.kt:193) $onCreate.onActivityStarted()FileDisplayActivity onStart() starting
I: 2023-06-05 18:45:55:930(AvatarManager.kt:87) .getAvatarForAccount()Avatar with imageKey a_admin@owncloud.segel.dev is not available in cache. Generating one...
D: 2023-06-05 18:45:55:931(SingleSessionManager.java:98) .getClientFor()getClientFor starting 
V: 2023-06-05 18:45:55:931(SingleSessionManager.java:125) .getClientFor()reusing client for account admin@owncloud.segel.dev
D: 2023-06-05 18:45:55:932(SingleSessionManager.java:180) .getClientFor()getClientFor finishing 
I: 2023-06-05 18:45:55:931(AvatarManager.kt:87) .getAvatarForAccount()Avatar with imageKey a_admin@owncloud.segel.dev is not available in cache. Generating one...
D: 2023-06-05 18:45:55:933(OwnCloudClient.java:129) .saveExecuteHttpMethod()Executing in request with id 9a3e11be-3272-401b-8547-7648a50375c7
D: 2023-06-05 18:45:55:942(BaseActivity.java:177) .onAccountSet()Account set: admin@owncloud.segel.dev
D: 2023-06-05 18:45:55:947(DrawerActivity.kt:446) .updateQuota()Update Quota
I: 2023-06-05 18:45:55:948(AvatarManager.kt:87) .getAvatarForAccount()Avatar with imageKey a_admin@owncloud.segel.dev is not available in cache. Generating one...
D: 2023-06-05 18:45:55:949(FileDisplayActivity.kt:342) .onAccountSet()Initializing Fragments in onAccountChanged..
D: 2023-06-05 18:45:55:950(ViewModelExt.kt:68) $runUseCaseWithResult.invokeSuspend()Use case executed: GetStoredQuotaUseCase with result: Success(data=UserQuota(accountName=admin@owncloud.segel.dev, available=-2, used=3763576))
I: 2023-06-05 18:45:55:951(AvatarManager.kt:87) .getAvatarForAccount()Avatar with imageKey a_admin@owncloud.segel.dev is not available in cache. Generating one...
D: 2023-06-05 18:45:55:951(SingleSessionManager.java:98) .getClientFor()getClientFor starting 
V: 2023-06-05 18:45:55:952(SingleSessionManager.java:125) .getClientFor()reusing client for account admin@owncloud.segel.dev
D: 2023-06-05 18:45:55:952(SingleSessionManager.java:180) .getClientFor()getClientFor finishing 
V: 2023-06-05 18:45:55:953(FileDisplayActivity.kt:745) .onResume()onResume() start
V: 2023-06-05 18:45:55:953(MainApp.kt:202) $onCreate.onActivityResumed()FileDisplayActivity onResume() starting
W: 2023-06-05 18:45:55:953(DrawerActivity.kt:558) .setDrawerMenuItemChecked()setDrawerMenuItemChecked has been called with invalid menu-item-ID
V: 2023-06-05 18:45:55:954(FileDisplayActivity.kt:767) .onResume()onResume() end
I: 2023-06-05 18:45:56:197(ReadRemoteFolderOperation.kt:97) .run()Synchronized / with 5 files. Operation finished with HTTP status code -1 (success)
D: 2023-06-05 18:45:56:197(OwnCloudClient.java:129) .saveExecuteHttpMethod()Executing in request with id 011312aa-8996-4560-ab98-d5caeaca3942
D: 2023-06-05 18:45:56:206(SingleSessionManager.java:98) .getClientFor()getClientFor starting 
V: 2023-06-05 18:45:56:206(SingleSessionManager.java:125) .getClientFor()reusing client for account admin@owncloud.segel.dev
D: 2023-06-05 18:45:56:207(SingleSessionManager.java:180) .getClientFor()getClientFor finishing 
D: 2023-06-05 18:45:56:268(GetRemoteUserInfoOperation.kt:58) .run()Successful response {"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":{"id":"admin","display-name":"Admin","email":"junn661@gmail.com","user-type":"primary"}}}
D: 2023-06-05 18:45:56:268(OwnCloudClient.java:129) .saveExecuteHttpMethod()Executing in request with id ac047a5e-f4cd-43f6-9d5f-d75a9374131d
D: 2023-06-05 18:45:56:270(GetRemoteUserInfoOperation.kt:68) .run()Get User Info completed and parsed to RemoteUserInfo(id=admin, displayName=Admin, email=junn661@gmail.com)
D: 2023-06-05 18:45:56:271(SyncProfileOperation.kt:56) $syncUserProfile.invokeSuspend()User info synchronized for account admin@owncloud.segel.dev
D: 2023-06-05 18:45:56:293(SingleSessionManager.java:98) .getClientFor()getClientFor starting 
V: 2023-06-05 18:45:56:294(SingleSessionManager.java:125) .getClientFor()reusing client for account admin@owncloud.segel.dev
D: 2023-06-05 18:45:56:295(SingleSessionManager.java:180) .getClientFor()getClientFor finishing 
I: 2023-06-05 18:45:56:347(ReadRemoteFileOperation.kt:72) .run()Read remote file /id_rsa with status 207
D: 2023-06-05 18:45:56:348(OwnCloudClient.java:129) .saveExecuteHttpMethod()Executing in request with id 48be36bb-71b1-474e-9633-e2b005d139a2
I: 2023-06-05 18:45:56:348(SynchronizeFileUseCase.kt:73) .run()Local file modification timestamp :1685957524000 and last sync date for data :1685957524142
I: 2023-06-05 18:45:56:349(SynchronizeFileUseCase.kt:74) .run()So it has changed locally: false
I: 2023-06-05 18:45:56:349(SynchronizeFileUseCase.kt:78) .run()Local etag :8597c9167c7d10cc461e5fb71d4a76cc and remote etag :8597c9167c7d10cc461e5fb71d4a76cc
I: 2023-06-05 18:45:56:350(SynchronizeFileUseCase.kt:79) .run()So it has changed remotely: false
I: 2023-06-05 18:45:56:351(SynchronizeFileUseCase.kt:105) .run()File id_rsa is already synchronized. Nothing to do here
V: 2023-06-05 18:45:56:351(MainApp.kt:210) $onCreate.onActivityStopped()SettingsActivity onStop() ending
D: 2023-06-05 18:45:56:353(SingleSessionManager.java:98) .getClientFor()getClientFor starting 
V: 2023-06-05 18:45:56:354(SingleSessionManager.java:125) .getClientFor()reusing client for account admin@owncloud.segel.dev
D: 2023-06-05 18:45:56:354(SingleSessionManager.java:180) .getClientFor()getClientFor finishing 
V: 2023-06-05 18:45:56:355(MainApp.kt:223) $onCreate.onActivityDestroyed()SettingsActivity onDestroy() ending
D: 2023-06-05 18:45:56:432(GetRemoteUserQuotaOperation.kt:102) .readData()Quota used: 3763576, QuotaAvailable: -2
D: 2023-06-05 18:45:56:432(OwnCloudClient.java:129) .saveExecuteHttpMethod()Executing in request with id 2e1beb10-c654-4042-978e-62dc407edf9b
I: 2023-06-05 18:45:56:433(GetRemoteUserQuotaOperation.kt:62) .run()Get quota completed: RemoteQuota(free=-2, used=3763576, total=0, relative=0.0) and message: Operation finished with HTTP status code -1 (success)
D: 2023-06-05 18:45:56:437(SyncProfileOperation.kt:71) $syncUserProfile.invokeSuspend()User quota synchronized for account admin@owncloud.segel.dev
D: 2023-06-05 18:45:56:438(SyncProfileOperation.kt:86) $syncUserProfile.invokeSuspend()Avatar for this account: admin@owncloud.segel.dev won't be synced due to capabilities 
I: 2023-06-05 18:45:56:517(ReadRemoteFileOperation.kt:72) .run()Read remote file /1.sh with status 207
I: 2023-06-05 18:45:56:518(SynchronizeFileUseCase.kt:73) .run()Local file modification timestamp :1685957523000 and last sync date for data :1685957523555
I: 2023-06-05 18:45:56:518(SynchronizeFileUseCase.kt:74) .run()So it has changed locally: false
I: 2023-06-05 18:45:56:519(SynchronizeFileUseCase.kt:78) .run()Local etag :68a84410a4080d6fe8b526b600a3cb9a and remote etag :68a84410a4080d6fe8b526b600a3cb9a
I: 2023-06-05 18:45:56:519(SynchronizeFileUseCase.kt:79) .run()So it has changed remotely: false
I: 2023-06-05 18:45:56:520(SynchronizeFileUseCase.kt:105) .run()File 1.sh is already synchronized. Nothing to do here
D: 2023-06-05 18:45:56:521(SingleSessionManager.java:98) .getClientFor()getClientFor starting 
V: 2023-06-05 18:45:56:522(SingleSessionManager.java:125) .getClientFor()reusing client for account admin@owncloud.segel.dev
D: 2023-06-05 18:45:56:522(SingleSessionManager.java:180) .getClientFor()getClientFor finishing 
D: 2023-06-05 18:45:56:523(OwnCloudClient.java:129) .saveExecuteHttpMethod()Executing in request with id a3eefdfa-23d9-4b09-a779-c121e7763dca
I: 2023-06-05 18:45:56:602(ReadRemoteFileOperation.kt:72) .run()Read remote file /id_rsa_arch with status 207
I: 2023-06-05 18:45:56:604(SynchronizeFileUseCase.kt:73) .run()Local file modification timestamp :1685957524000 and last sync date for data :1685957524304
I: 2023-06-05 18:45:56:604(SynchronizeFileUseCase.kt:74) .run()So it has changed locally: false
I: 2023-06-05 18:45:56:605(SynchronizeFileUseCase.kt:78) .run()Local etag :95b49ba567b7617aefdd4a42f205b380 and remote etag :95b49ba567b7617aefdd4a42f205b380
I: 2023-06-05 18:45:56:605(SynchronizeFileUseCase.kt:79) .run()So it has changed remotely: false
I: 2023-06-05 18:45:56:606(SynchronizeFileUseCase.kt:105) .run()File id_rsa_arch is already synchronized. Nothing to do here
D: 2023-06-05 18:45:56:606(ViewModelExt.kt:68) $runUseCaseWithResult.invokeSuspend()Use case executed: SynchronizeFolderUseCase with result: Success(data=kotlin.Unit)
D: 2023-06-05 18:45:56:736(SingleSessionManager.java:98) .getClientFor()getClientFor starting 
V: 2023-06-05 18:45:56:736(SingleSessionManager.java:125) .getClientFor()reusing client for account admin@owncloud.segel.dev
D: 2023-06-05 18:45:56:737(SingleSessionManager.java:180) .getClientFor()getClientFor finishing 
D: 2023-06-05 18:45:56:737(OwnCloudClient.java:129) .saveExecuteHttpMethod()Executing in request with id d17a7e7d-9371-4293-8f37-0d7697e13af9
D: 2023-06-05 18:45:56:744(SingleSessionManager.java:98) .getClientFor()getClientFor starting 
V: 2023-06-05 18:45:56:744(SingleSessionManager.java:125) .getClientFor()reusing client for account admin@owncloud.segel.dev
D: 2023-06-05 18:45:56:745(SingleSessionManager.java:180) .getClientFor()getClientFor finishing 
D: 2023-06-05 18:45:56:806(OwnCloudClient.java:129) .saveExecuteHttpMethod()Executing in request with id d98953d7-a226-4220-9aa7-b12d79befb9f
D: 2023-06-05 18:45:56:806(GetRemoteCapabilitiesOperation.kt:71) .run()Successful response {"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":{"capabilities":{"core":{"pollinterval":60,"webdav-root":"remote.php/webdav","status":{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"10.11.0.0","versionstring":"10.11.0","edition":"Community","productname":"Infinite Scale","product":"Infinite Scale","productversion":"2.0.0"},"support-url-signing":true},"checksums":{"supportedTypes":["sha1","md5","adler32"],"preferredUploadType":"sha1"},"files":{"privateLinks":true,"bigfilechunking":false,"undelete":true,"versioning":true,"favorites":false,"blacklisted_files":[],"tus_support":{"version":"1.0.0","resumable":"1.0.0","extension":"creation,creation-with-upload","max_chunk_size":100000000,"http_method_override":""},"archivers":[{"enabled":true,"version":"2.0.0","formats":["tar","zip"],"archiver_url":"/archiver","max_num_files":"10000","max_size":"1073741824"}],"app_providers":[{"enabled":true,"version":"1.1.0","apps_url":"/app/list","open_url":"/app/open","open_web_url":"/app/open-with-web","new_url":"/app/new"}]},"dav":{"chunking":"","trashbin":"1.0","reports":["search-files"],"chunkingParallelUploadDisabled":false},"files_sharing":{"api_enabled":true,"resharing":true,"group_sharing":true,"sharing_roles":true,"deny_access":false,"auto_accept_share":true,"share_with_group_members_only":true,"share_with_membership_groups_only":true,"search_min_length":3,"default_permissions":22,"user_enumeration":{"enabled":true,"group_members_only":true},"federation":{"outgoing":false,"incoming":false},"public":{"enabled":true,"send_mail":true,"social_share":true,"upload":true,"multiple":true,"supports_upload_only":true,"password":{"enforced_for":{"read_only":false,"read_write":false,"upload_only":false},"enforced":false},"expire_date":{"enabled":false},"can_edit":true,"alias":true},"user":{"send_mail":true,"profile_picture":false,"settings":[{"enabled":true,"version":"1.0.0"}]}},"spaces":{"version":"1.0.0","enabled":true,"projects":true,"share_jail":true}},"version":{"major":10,"minor":11,"micro":0,"string":"10.11.0","edition":"Community","product":"Infinite Scale","productversion":"2.0.0"}}}}
D: 2023-06-05 18:45:56:811(GetRemoteCapabilitiesOperation.kt:82) .run()Get Capabilities completed and parsed to RemoteCapability(accountName=, versionMajor=10, versionMinor=11, versionMicro=0, versionString=10.11.0, versionEdition=Community, corePollinterval=60, chunkingVersion=, filesSharingApiEnabled=TRUE, filesSharingPublicEnabled=TRUE, filesSharingPublicPasswordEnforced=FALSE, filesSharingPublicPasswordEnforcedReadOnly=FALSE, filesSharingPublicPasswordEnforcedReadWrite=FALSE, filesSharingPublicPasswordEnforcedUploadOnly=FALSE, filesSharingPublicExpireDateEnabled=FALSE, filesSharingPublicExpireDateDays=0, filesSharingPublicExpireDateEnforced=FALSE, filesSharingPublicUpload=TRUE, filesSharingPublicMultiple=TRUE, filesSharingPublicSupportsUploadOnly=TRUE, filesSharingResharing=TRUE, filesSharingFederationOutgoing=FALSE, filesSharingFederationIncoming=FALSE, filesSharingUserProfilePicture=FALSE, filesBigFileChunking=FALSE, filesUndelete=TRUE, filesVersioning=TRUE, filesPrivateLinks=TRUE, filesAppProviders=[RemoteAppProviders(eJun 05 18:44:39 odroid-m1 ocis[465192]: {"level":"warn","service":"frontend","pkg":"rhttp","traceid":"00000000000000000000000000000000","time":"2023-06-05T18:44:39.152882503+09:00","message":"core access token not set"}
Jun 05 18:45:57 odroid-m1 ocis[465192]: {"level":"warn","service":"frontend","pkg":"rhttp","traceid":"00000000000000000000000000000000","time":"2023-06-05T18:45:57.272027843+09:00","message":"core access token not set"}
Jun 05 18:46:29 odroid-m1 ocis[465192]: {"level":"warn","service":"frontend","pkg":"rhttp","traceid":"00000000000000000000000000000000","time":"2023-06-05T18:46:29.015873845+09:00","message":"core access token not set"}
Jun 05 18:46:29 odroid-m1 ocis[465192]: {"level":"warn","service":"frontend","pkg":"rhttp","traceid":"00000000000000000000000000000000","time":"2023-06-05T18:46:29.225668336+09:00","message":"core access token not set"}
Jun 05 18:47:09 odroid-m1 ocis[465192]: {"level":"warn","service":"frontend","pkg":"rhttp","traceid":"00000000000000000000000000000000","time":"2023-06-05T18:47:09.407889947+09:00","message":"core access token not set"}
nabled=true, version=1.1.0, appsUrl=/app/list, openUrl=/app/open, openWebUrl=/app/open-with-web, newUrl=/app/new)], spaces=RemoteSpaces(enabled=true, projects=true, shareJail=true))
D: 2023-06-05 18:45:56:818(SingleSessionManager.java:98) .getClientFor()getClientFor starting 
V: 2023-06-05 18:45:56:819(SingleSessionManager.java:125) .getClientFor()reusing client for account admin@owncloud.segel.dev
D: 2023-06-05 18:45:56:820(SingleSessionManager.java:180) .getClientFor()getClientFor finishing 
I: 2023-06-05 18:45:56:894(ReadRemoteFileOperation.kt:72) .run()Read remote file /Caskaydia Cove Regular Nerd Font Complete Mono.otf with status 207
D: 2023-06-05 18:45:56:895(OwnCloudClient.java:129) .saveExecuteHttpMethod()Executing in request with id 97b24b22-4ce7-44b7-94b3-8a41d2f705dc
I: 2023-06-05 18:45:56:896(SynchronizeFileUseCase.kt:66) .run()File Caskaydia Cove Regular Nerd Font Complete Mono.otf is not downloaded. Let's download it
I: 2023-06-05 18:45:56:898(DownloadFileUseCase.kt:103) .enqueueNewDownload()Download of Caskaydia Cove Regular Nerd Font Complete Mono.otf has been enqueued.
D: 2023-06-05 18:45:56:899(ViewModelExt.kt:68) $runUseCaseWithResult.invokeSuspend()Use case executed: SynchronizeFileUseCase with result: Success(data=DownloadEnqueued(workerId=d08c820d-5c88-44cc-8a0c-41a23ec1fd2e))
D: 2023-06-05 18:45:56:941(GetRemoteAppRegistryOperation.kt:55) .run()Successful response {"mime-types":[]}
D: 2023-06-05 18:45:56:943(GetRemoteAppRegistryOperation.kt:65) .run()Get AppRegistry completed and parsed to AppRegistryResponse(value=[])
D: 2023-06-05 18:45:56:965(SingleSessionManager.java:98) .getClientFor()getClientFor starting 
V: 2023-06-05 18:45:56:965(SingleSessionManager.java:125) .getClientFor()reusing client for account admin@owncloud.segel.dev
D: 2023-06-05 18:45:56:966(SingleSessionManager.java:180) .getClientFor()getClientFor finishing 
D: 2023-06-05 18:45:56:967(OwnCloudClient.java:129) .saveExecuteHttpMethod()Executing in request with id cf67aea8-29af-42b0-a568-e0723572112b
E: 2023-06-05 18:45:58:158(DownloadRemoteFileOperation.kt:144) .downloadFile()Content-Length not equal to transferred bytes.
D: 2023-06-05 18:45:58:159(DownloadRemoteFileOperation.kt:145) .downloadFile()totalToTransfer = 0, transferred = 3754928
I: 2023-06-05 18:45:58:163(DownloadRemoteFileOperation.kt:70) .run()Download of /Caskaydia Cove Regular Nerd Font Complete Mono.otf to /data/user/0/com.owncloud.android/files/owncloud/tmp/admin@owncloud.segel.dev/cd690cad-5f73-4d8f-8548-9f331ce2e86e$240463e8-ac4f-431b-912e-a75eff1c7f53/Caskaydia Cove Regular Nerd Font Complete Mono.otf: Operation finished with HTTP status code -1 (success)
E: 2023-06-05 18:45:58:165(DownloadFileWorker.kt:127) .doWork()com.owncloud.android.domain.exceptions.LocalStorageNotMovedException
	at com.owncloud.android.workers.DownloadFileWorker.moveTemporalFileToFinalLocation(DownloadFileWorker.kt:200)
	at com.owncloud.android.workers.DownloadFileWorker.doWork(DownloadFileWorker.kt:123)
	at androidx.work.CoroutineWorker$startWork$1.invokeSuspend(CoroutineWorker.kt:68)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by jesmrec** [comment]
Could you share with us your server URL with a test account? not reproducible on my side. You can send it to `android-app@owncloud.com`. It would be very helpful.

**Comment by segln** [comment]
> Could you share with us your server URL with a test account? not reproducible on my side. You can send it to `android-app@owncloud.com`. It would be very helpful.

I think it is Android file permisison problem, it never asked allowing file permisisons. But OK. 

## URL
https://owncloud.segel.dev/

## username/passwd
test/test

I shared a file. It can be found in `Shares`.

**Comment by jesmrec** [comment]
@segln i'd recommend you not to post credentials and URL here since this is an open site and anyone could access your server, who knows if evil intentions.

**Comment by jesmrec** [comment]
@JuancaG05 @manuelplazaspalacio could you take a look?

**Comment by segln** [comment]
> @segln i'd recommend you not to post credentials and URL here since this is an open site and anyone could access your server, who knows if evil intentions.

I set `test` user as guest and have only one file for test. So... maybe ok, I think.

**Comment by JuancaG05** [comment]
Hi @segln! I'm not able to login with the test user you provided, it seems to provoke an error. Also, the server seems to be very slow until the app can find it. Could it be a server-related problem? I'll wait for your response 😁👍

**Comment by michaelstingl** [comment]
can't with the information provided, but can be re-opened whenever it's needed…
