### ISSUE TITLE
[BUG] Crash in the app when it is in background

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4102]
From time to time, with the app not in foreground the crash dialog appears. This is the stack trace:

```
2023-07-14 10:15:48.302 26310-26310/com.owncloud.android.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.owncloud.android.debug, PID: 26310
    android.net.ConnectivityManager$TooManyRequestsException
        at android.net.ConnectivityManager.convertServiceException(ConnectivityManager.java:3511)
        at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3699)
        at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4191)
        at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4158)
        at androidx.work.impl.utils.NetworkApi24.registerDefaultNetworkCallbackCompat(NetworkApi24.kt:28)
        at androidx.work.impl.constraints.trackers.NetworkStateTracker24.startTracking(NetworkStateTracker.kt:139)
        at androidx.work.impl.constraints.trackers.ConstraintTracker.addListener(ConstraintTracker.kt:57)
        at androidx.work.impl.constraints.controllers.ConstraintController.replace(ConstraintController.kt:82)
        at androidx.work.impl.constraints.WorkConstraintsTrackerImpl.replace(WorkConstraintsTracker.kt:92)
        at androidx.work.impl.background.greedy.GreedyScheduler.schedule(GreedyScheduler.java:170)
        at androidx.work.impl.background.greedy.DelayedWorkTracker$1.run(DelayedWorkTracker.java:75)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Seems to be a problem with the number of requests. Is there any limite set by the network library? 

Pixel2
Android11

**Comment by jesmrec** [comment]
didn't notice the crash anymore.

i case it is again there, i'll reopen.
