### ISSUE TITLE
[BUG] Crash when the token is expired

### ISSUE THREAD

**Issue by Aitorbp** [owncloud/android#4116]
### Actual behaviour
- When the token is expired and you change list view for grid view the app crash. It could happen too when user change the screen. To fix that you have to click on Sign in and start log in process again. After that everything works good.
### Expected behaviour
- It shouldn´t be any crash when the token is expired. The server should generate a new one.
 
### Steps to reproduce
1. Wait until appear the dialog where said: The token is expired. Sign in. 
2. Click on grid view.
3. The crash should appear.

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version:

Device model: Pixel A3 API 34 (Emulator)

Stock or customized system:

ownCloud app version:  Owncloud debbug version 4.0

ownCloud server version:

### Logs
`2023-08-01 10:53:15.099 20295-20310 (TokenRequ...77) .run() com.owncloud.android.debug           E  Failed response while getting tokens from the server status code: 400; response message: {
                                                                                                      "error": "invalid_request",
                                                                                                      "error_description": "crypto/rsa: verification error"
                                                                                                    }
2023-08-01 10:53:15.100 20295-20310 (RemoteOpe... .<init>() com.owncloud.android.debug           D  RemoteOperationResult has processed UNHANDLED_HTTP_CODE: 400 Bad Request
2023-08-01 10:53:15.102 20295-20310 (TokenRequ...82) .run() com.owncloud.android.debug           E  Exception while getting tokens
                                                                                                    java.lang.IllegalStateException: closed
                                                                                                        at okio.RealBufferedSource.select(RealBufferedSource.kt:218)
                                                                                                        at okhttp3.internal.Util.readBomAsCharset(Util.kt:265)
                                                                                                        at okhttp3.ResponseBody.string(ResponseBody.kt:187)
                                                                                                        at com.owncloud.android.lib.common.http.methods.HttpBaseMethod.getResponseBodyAsString(HttpBaseMethod.kt:138)
                                                                                                        at com.owncloud.android.lib.common.operations.RemoteOperationResult.<init>(RemoteOperationResult.java:197)
                                                                                                        at com.owncloud.android.lib.resources.oauth.TokenRequestRemoteOperation.run(TokenRequestRemoteOperation.kt:78)
                                                                                                        at com.owncloud.android.lib.common.operations.RemoteOperation.runOperation(RemoteOperation.java:264)
                                                                                                        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:229)
                                                                                                        at com.owncloud.android.lib.resources.oauth.services.implementation.OCOIDCService.performTokenRequest(OCOIDCService.kt:49)
                                                                                                        at com.owncloud.android.data.oauth.datasources.implementation.OCRemoteOAuthDataSource$performTokenRequest$tokenResponse$1.invoke(OCRemoteOAuthDataSource.kt:58)
                                                                                                        at com.owncloud.android.data.oauth.datasources.implementation.OCRemoteOAuthDataSource$performTokenRequest$tokenResponse$1.invoke(OCRemoteOAuthDataSource.kt:57)
                                                                                                        at com.owncloud.android.data.RemoteOperationHandlerKt.executeRemoteOperation(RemoteOperationHandler.kt:79)
                                                                                                        at com.owncloud.android.data.oauth.datasources.implementation.OCRemoteOAuthDataSource.performTokenRequest(OCRemoteOAuthDataSource.kt:57)
                                                                                                        at com.owncloud.android.data.oauth.repository.OCOAuthRepository.performTokenRequest(OCOAuthRepository.kt:38)
                                                                                                        at com.owncloud.android.domain.authentication.oauth.RequestTokenUseCase.run(RequestTokenUseCase.kt:30)
                                                                                                        at com.owncloud.android.domain.authentication.oauth.RequestTokenUseCase.run(RequestTokenUseCase.kt:25)
                                                                                                        at com.owncloud.android.domain.BaseUseCaseWithResult.execute(BaseUseCaseWithResult.kt:30)
                                                                                                        at com.owncloud.android.presentation.authentication.AccountAuthenticator.refreshToken(AccountAuthenticator.java:383)
                                                                                                        at com.owncloud.android.presentation.authentication.AccountAuthenticator.getAuthToken(AccountAuthenticator.java:177)
                                                                                                        at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:251)
                                                                                                        at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:253)
                                                                                                        at android.os.Binder.execTransactInternal(Binder.java:1344)
                                                                                                        at android.os.Binder.execTransact(Binder.java:1275)
2023-08-01 10:53:15.109 20295-20310 (RemoteOpe... .<init>() com.owncloud.android.debug           E  ---------------------------------
                                                                                                    Create RemoteOperationResult from exception.
                                                                                                     Message: IllegalStateException: closed
                                                                                                     Stacktrace: java.lang.IllegalStateException: closed
                                                                                                        at okio.RealBufferedSource.select(RealBufferedSource.kt:218)
                                                                                                        at okhttp3.internal.Util.readBomAsCharset(Util.kt:265)
                                                                                                        at okhttp3.ResponseBody.string(ResponseBody.kt:187)
                                                                                                        at com.owncloud.android.lib.common.http.methods.HttpBaseMethod.getResponseBodyAsString(HttpBaseMethod.kt:138)
                                                                                                        at com.owncloud.android.lib.common.operations.RemoteOperationResult.<init>(RemoteOperationResult.java:197)
                                                                                                        at com.owncloud.android.lib.resources.oauth.TokenRequestRemoteOperation.run(TokenRequestRemoteOperation.kt:78)
                                                                                                        at com.owncloud.android.lib.common.operations.RemoteOperation.runOperation(RemoteOperation.java:264)
                                                                                                        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:229)
                                                                                                        at com.owncloud.android.lib.resources.oauth.services.implementation.OCOIDCService.performTokenRequest(OCOIDCService.kt:49)
                                                                                                        at com.owncloud.android.data.oauth.datasources.implementation.OCRemoteOAuthDataSource$performTokenRequest$tokenResponse$1.invoke(OCRemoteOAuthDataSource.kt:58)
                                                                                                        at com.owncloud.android.data.oauth.datasources.implementation.OCRemoteOAuthDataSource$performTokenRequest$tokenResponse$1.invoke(OCRemoteOAuthDataSource.kt:57)
                                                                                                        at com.owncloud.android.data.RemoteOperationHandlerKt.executeRemoteOperation(RemoteOperationHandler.kt:79)
                                                                                                        at com.owncloud.android.data.oauth.datasources.implementation.OCRemoteOAuthDataSource.performTokenRequest(OCRemoteOAuthDataSource.kt:57)
                                                                                                        at com.owncloud.android.data.oauth.repository.OCOAuthRepository.performTokenRequest(OCOAuthRepository.kt:38)
                                                                                                        at com.owncloud.android.domain.authentication.oauth.RequestTokenUseCase.run(RequestTokenUseCase.kt:30)
                                                                                                        at com.owncloud.android.domain.authentication.oauth.RequestTokenUseCase.run(RequestTokenUseCase.kt:25)
                                                                                                        at com.owncloud.android.domain.BaseUseCaseWithResult.execute(BaseUseCaseWithResult.kt:30)
                                                                                                        at com.owncloud.android.presentation.authentication.AccountAuthenticator.refreshToken(AccountAuthenticator.java:383)
                                                                                                        at com.owncloud.android.presentation.authentication.AccountAuthenticator.getAuthToken(AccountAuthenticator.java:177)
                                                                                                        at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:251)
                                                                                                        at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:253)
                                                                                                        at android.os.Binder.execTransactInternal(Binder.java:1344)
                                                                                                        at android.os.Binder.execTransact(Binder.java:1275)
 
2023-08-01 10:53:15.113 20295-20310 (AccountAu...eshToken() com.owncloud.android.debug           E  OAuth request to refresh access token failed. Preparing to access Login Activity
                                                                                                    com.owncloud.android.domain.exceptions.ServerNotReachableException
                                                                                                        at com.owncloud.android.data.RemoteOperationHandlerKt.handleRemoteOperationResult(RemoteOperationHandler.kt:98)
                                                                                                        at com.owncloud.android.data.RemoteOperationHandlerKt.executeRemoteOperation(RemoteOperationHandler.kt:80)
                                                                                                        at com.owncloud.android.data.oauth.datasources.implementation.OCRemoteOAuthDataSource.performTokenRequest(OCRemoteOAuthDataSource.kt:57)
                                                                                                        at com.owncloud.android.data.oauth.repository.OCOAuthRepository.performTokenRequest(OCOAuthRepository.kt:38)
                                                                                                        at com.owncloud.android.domain.authentication.oauth.RequestTokenUseCase.run(RequestTokenUseCase.kt:30)
                                                                                                        at com.owncloud.android.domain.authentication.oauth.RequestTokenUseCase.run(RequestTokenUseCase.kt:25)
                                                                                                        at com.owncloud.android.domain.BaseUseCaseWithResult.execute(BaseUseCaseWithResult.kt:30)
                                                                                                        at com.owncloud.android.presentation.authentication.AccountAuthenticator.refreshToken(AccountAuthenticator.java:383)
                                                                                                        at com.owncloud.android.presentation.authentication.AccountAuthenticator.getAuthToken(AccountAuthenticator.java:177)
                                                                                                        at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:251)
                                                                                                        at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:253)
                                                                                                        at android.os.Binder.execTransactInternal(Binder.java:1344)
                                                                                                        at android.os.Binder.execTransact(Binder.java:1275)`

**Comment by jesmrec** [comment]
Seems to happen because an incorrect call done from the main thread. Needs a fix.

**Comment by butonic** [comment]
Is this the same problem:
```
java.lang.IllegalStateException: calling this from your main thread can lead to deadlock
	at android.accounts.AccountManager.ensureNotOnMainThread(AccountManager.java:2301)
	at android.accounts.AccountManager.access$500(AccountManager.java:167)
	at android.accounts.AccountManager$AmsTask.internalGetResult(AccountManager.java:2407)
	at android.accounts.AccountManager$AmsTask.getResult(AccountManager.java:2445)
	at android.accounts.AccountManager$AmsTask.getResult(AccountManager.java:2360)
	at android.accounts.AccountManager.blockingGetAuthToken(AccountManager.java:1649)
	at com.owncloud.android.lib.common.accounts.AccountUtils.getCredentialsForAccount(AccountUtils.java:116)
	at com.owncloud.android.lib.common.OwnCloudAccount.loadCredentials(OwnCloudAccount.java:121)
	at com.owncloud.android.lib.common.SingleSessionManager.getClientFor(SingleSessionManager.java:162)
	at com.owncloud.android.data.ClientManager.getClientForAccount(ClientManager.kt:108)
	at com.owncloud.android.data.ClientManager.getClientForCoilThumbnails(ClientManager.kt:127)
	at com.owncloud.android.presentation.thumbnails.ThumbnailsRequester.getOwnCloudClient(ThumbnailsRequester.kt:123)
	at com.owncloud.android.presentation.thumbnails.ThumbnailsRequester.getPreviewUriForFile(ThumbnailsRequester.kt:102)
	at com.owncloud.android.presentation.files.filelist.FileListAdapter.onBindViewHolder(FileListAdapter.kt:292)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
	at androidx.recyclerview.widget.LayoutState.next(LayoutState.java:98)
	at androidx.recyclerview.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1581)
	at androidx.recyclerview.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:691)
	at androidx.recyclerview.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:604)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:868)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3858)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3308)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2272)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8999)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1160)
	at android.view.Choreographer.doCallbacks(Choreographer.java:950)
	at android.view.Choreographer.doFrame(Choreographer.java:879)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1142)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
```

When I open the app it instantly crashes...
