### ISSUE TITLE
IllegalStateException when opening the app

### ISSUE THREAD

**Issue by butonic** [owncloud/android#4125]
When my wife opens the app it instantly crashes:
```
java.lang.IllegalStateException: calling this from your main thread can lead to deadlock
	at android.accounts.AccountManager.ensureNotOnMainThread(AccountManager.java:2301)
	at android.accounts.AccountManager.access$500(AccountManager.java:167)
	at android.accounts.AccountManager$AmsTask.internalGetResult(AccountManager.java:2407)
	at android.accounts.AccountManager$AmsTask.getResult(AccountManager.java:2445)
	at android.accounts.AccountManager$AmsTask.getResult(AccountManager.java:2360)
	at android.accounts.AccountManager.blockingGetAuthToken(AccountManager.java:1649)
	at com.owncloud.android.lib.common.accounts.AccountUtils.getCredentialsForAccount(AccountUtils.java:116)
	at com.owncloud.android.lib.common.OwnCloudAccount.loadCredentials(OwnCloudAccount.java:121)
	at com.owncloud.android.lib.common.SingleSessionManager.getClientFor(SingleSessionManager.java:162)
	at com.owncloud.android.data.ClientManager.getClientForAccount(ClientManager.kt:108)
	at com.owncloud.android.data.ClientManager.getClientForCoilThumbnails(ClientManager.kt:127)
	at com.owncloud.android.presentation.thumbnails.ThumbnailsRequester.getOwnCloudClient(ThumbnailsRequester.kt:123)
	at com.owncloud.android.presentation.thumbnails.ThumbnailsRequester.getPreviewUriForFile(ThumbnailsRequester.kt:102)
	at com.owncloud.android.presentation.files.filelist.FileListAdapter.onBindViewHolder(FileListAdapter.kt:292)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
	at androidx.recyclerview.widget.LayoutState.next(LayoutState.java:98)
	at androidx.recyclerview.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1581)
	at androidx.recyclerview.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:691)
	at androidx.recyclerview.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:604)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:868)
	at android.view.View.layout(View.java:23550)
	at android.view.ViewGroup.layout(ViewGroup.java:6452)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3858)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3308)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2272)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8999)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1160)
	at android.view.Choreographer.doCallbacks(Choreographer.java:950)
	at android.view.Choreographer.doFrame(Choreographer.java:879)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1142)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
```

I had to restart the server last week, which uses OpenID connect and the session likely got removed.

**Comment by jesmrec** [comment]
Thanks for reporting, team will take a look.

**Comment by Aitorbp** [comment]
Hi, this issue will be fixed in this [pull request](https://github.com/owncloud/android/pull/4128).

**Comment by jesmrec** [comment]
@butonic could you check in 4.1.0 version fixes the problem? since the attached PR was already released there. Thanks in advance.

**Comment by Aitorbp** [comment]
Closing this issue. Feel free to reopen again if still happens.
