### ISSUE TITLE
[BUG] Can't stream video from space

### ISSUE THREAD

**Issue by LiYuHan525** [owncloud/android#4328]
### Actual behaviour
-can play video from person file via android
-cant play video from spaces file via android
-can play the same video from space via web

### Expected behaviour
-can play video from spaces
 
### Steps to reproduce
1. go to any space
2. play video
3. alert"This video file is no longer available in the server"

Can this problem be reproduced with the official owncloud server?
(url: https://demo.owncloud.org, user: test, password: test)

### Environment data
Android version:
14
Device model: 
Xiaomi 13 pro
Stock or customized system:

ownCloud app version:
4.2.0
ownCloud server version:
ocis 4.0.5
#### Web server error log

when req from android, the path url is based on 'files' not 'spaces' like from web
```
{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"truenas/i2B5NthcwU-000874","traceid":"e111abbc5ebab9e67f2235bc399f7e0d","remote-addr":"192.168.50.250:59306","method":"GET","status":404,"path":"/remote.php/dav/files/admin/file.mp4","duration":19.66575,"bytes":0,"time":"2024-02-22T02:44:58.979287577Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}

{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"cf76d3b2-eaf4-4e27-bd9e-c96406ae0d35","traceid":"a27f968611ee49dbe954c7044940659a","remote-addr":"192.168.50.250:57546","method":"PROPFIND","status":207,"path":"/remote.php/dav/spaces/cd95daef-266c-4fe5-9235-ae114f3c81c0$35a7805c-51b3-49ea-9e5f-073cd2fdaabf/file.mp4","duration":25.171966,"bytes":575,"time":"2024-02-22T02:41:22.832133814Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:34","message":"access-log"}
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by jesmrec** [comment]
Thanks a lot for reporting. I can reproduce the problem, team will fix.

**Comment by jesmrec** [comment]
stacktrace:

```
15:00:48.893  W  Key START_POSITION expected Long but value was a java.lang.Integer.  The default value 0 was returned.
15:00:48.894  W  Attempt to cast generated internal exception:
                 java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
                 	at android.os.BaseBundle.getLong(BaseBundle.java:1111)
                 	at android.content.Intent.getLongExtra(Intent.java:8200)
                 	at com.owncloud.android.ui.preview.PreviewVideoActivity.onCreate(PreviewVideoActivity.kt:117)
                 	at android.app.Activity.performCreate(Activity.java:8000)
                 	at android.app.Activity.performCreate(Activity.java:7984)
                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
                 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loop(Looper.java:223)
                 	at android.app.ActivityThread.main(ActivityThread.java:7656)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by JuancaG05** [comment]
It seems this only happens with video streaming, and because the URL we send to Exoplayer is malformed (lacks of space reference). Working on it 🚀
