### ISSUE TITLE
[BUG] Audio player does not work

### ISSUE THREAD

**Issue by jesmrec** [owncloud/android#4474]
### Steps to reproduce

Play any audio file

### Actual behaviour

`Unexpected error trying to play...`

i caught the following stacktrace:

```
E: IllegalStateException user1@<server>/<filename> (Ask Gemini)
                 android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{1ebcada 29147:com.owncloud.android.debug/u0a202} targetSDK=34
                 	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
                 	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
                 	at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
                 	at android.os.Parcel.readParcelable(Parcel.java:4852)
                 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
                 	at android.os.Parcel.createException(Parcel.java:3041)
                 	at android.os.Parcel.readException(Parcel.java:3024)
                 	at android.os.Parcel.readException(Parcel.java:2966)
                 	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7280)
                 	at android.app.Service.startForeground(Service.java:775)
                 	at com.owncloud.android.media.MediaService.setUpAsForeground(MediaService.java:626)
                 	at com.owncloud.android.media.MediaService.playMedia(MediaService.java:484)
                 	at com.owncloud.android.media.MediaService.processPlayFileRequest(MediaService.java:299)
                 	at com.owncloud.android.media.MediaService.onStartCommand(MediaService.java:267)
                 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5053)
                 	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2435)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loopOnce(Looper.java:224)
                 	at android.os.Looper.loop(Looper.java:318)
                 	at android.app.ActivityThread.main(ActivityThread.java:8763)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

### Expected behaviour

File played
 
Reproduced in the current stable `4.3.1` with Android 14

**Comment by jesmrec** [comment]
Checking with different Android versions:

9 -> not reproducible
10 -> not reproducible
11 -> not reproducible
12 ->
13 -> 
14 -> reproducible
