### ISSUE TITLE
 Android client crashes when viewing InstantUpload folder #3068 

### ISSUE THREAD

**Issue by ongobongo** [owncloud/android#935]
The folder has 281 images and scrolling by swiping causes it to crash every time.

**Comment by tobiasKaminsky** [comment]
I think we need a LogCat output for debugging this.

**Comment by ongobongo** [comment]
```
[ 04-06 11:26:50.166 12669:12669 E/AndroidRuntime ]

FATAL EXCEPTION: main

Process: com.owncloud.android, PID: 12669

java.lang.OutOfMemoryError: Failed to allocate a 589836 byte allocation with 325188 free bytes and 317KB until OOM

	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)

	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)

	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:773)

	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:749)

	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:787)

	at com.owncloud.android.ui.adapter.DiskLruImageCache.getBitmap(DiskLruImageCache.java:123)

	at com.owncloud.android.datamodel.ThumbnailsCacheManager.getBitmapFromDiskCache(ThumbnailsCacheManager.java:134)

	at com.owncloud.android.ui.adapter.FileListListAdapter.getView(FileListListAdapter.java:278)

	at third_parties.in.srain.cube.GridViewWithHeaderAndFooter$HeaderViewGridAdapter.getView(GridViewWithHeaderAndFooter.java:657)

	at android.widget.AbsListView.obtainView(AbsListView.java:2823)

	at android.widget.GridView.makeAndAddView(GridView.java:1437)

	at android.widget.GridView.makeRow(GridView.java:361)

	at android.widget.GridView.fillUp(GridView.java:402)

	at android.widget.GridView.fillGap(GridView.java:277)

	at android.widget.AbsListView.trackMotionScroll(AbsListView.java:7040)

	at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:6478)

	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)

	at android.view.Choreographer.doCallbacks(Choreographer.java:590)

	at android.view.Choreographer.doFrame(Choreographer.java:559)

	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)

	at android.os.Handler.handleCallback(Handler.java:739)

	at android.os.Handler.dispatchMessage(Handler.java:95)

	at android.os.Looper.loop(Looper.java:145)

	at android.app.ActivityThread.main(ActivityThread.java:5942)

	at java.lang.reflect.Method.invoke(Native Method)

	at java.lang.reflect.Method.invoke(Method.java:372)

	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)

	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)
```

**Comment by masensio** [comment]
Hi @ongobongo,
thanks for your feedback.
I think this is the same problem that #905. Please track it there.
