### ISSUE TITLE
Crash on share action from Photos application

### ISSUE THREAD

**Issue by smarek** [owncloud/android#937]
Running version 1.7.0 from f-droid
Selected two photos from Photos application, received two separate crashes (one for each photo i guess?)

**first**
```
--------- beginning of crash
E/AndroidRuntime( 4411): FATAL EXCEPTION: main
E/AndroidRuntime( 4411): Process: com.owncloud.android, PID: 4411
E/AndroidRuntime( 4411): java.lang.RuntimeException: Unable to start service com.owncloud.android.files.services.FileUploader@2dd9a0d with Intent { cmp=com.owncloud.android/.files.services.FileUploader (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
E/AndroidRuntime( 4411): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2911)
E/AndroidRuntime( 4411): 	at android.app.ActivityThread.access$2100(ActivityThread.java:151)
E/AndroidRuntime( 4411): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
E/AndroidRuntime( 4411): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 4411): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 4411): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 4411): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4411): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 4411): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 4411): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime( 4411): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
E/AndroidRuntime( 4411): 	at com.owncloud.android.files.services.FileUploader.isPdfFileFromContentProviderWithoutExtension(FileUploader.java:896)
E/AndroidRuntime( 4411): 	at com.owncloud.android.files.services.FileUploader.obtainNewOCFileToUpload(FileUploader.java:685)
E/AndroidRuntime( 4411): 	at com.owncloud.android.files.services.FileUploader.onStartCommand(FileUploader.java:270)
E/AndroidRuntime( 4411): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2894)
E/AndroidRuntime( 4411): 	... 9 more
```

**second**
```
D/AndroidRuntime(31994): Shutting down VM
E/AndroidRuntime(31994): FATAL EXCEPTION: main
E/AndroidRuntime(31994): Process: com.owncloud.android, PID: 31994
E/AndroidRuntime(31994): java.lang.RuntimeException: Unable to start service com.owncloud.android.files.services.FileUploader@2a43b9d8 with Intent { cmp=com.owncloud.android/.files.services.FileUploader (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
E/AndroidRuntime(31994): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2911)
E/AndroidRuntime(31994): 	at android.app.ActivityThread.access$2100(ActivityThread.java:151)
E/AndroidRuntime(31994): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1401)
E/AndroidRuntime(31994): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(31994): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(31994): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(31994): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31994): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(31994): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(31994): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime(31994): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
E/AndroidRuntime(31994): 	at com.owncloud.android.files.services.FileUploader.isPdfFileFromContentProviderWithoutExtension(FileUploader.java:896)
E/AndroidRuntime(31994): 	at com.owncloud.android.files.services.FileUploader.obtainNewOCFileToUpload(FileUploader.java:685)
E/AndroidRuntime(31994): 	at com.owncloud.android.files.services.FileUploader.onStartCommand(FileUploader.java:270)
E/AndroidRuntime(31994): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2894)
E/AndroidRuntime(31994): 	... 9 more
```

**Comment by masensio** [comment]
Hi @smarek,

thanks for your feedback.
I think this issue and #930 are the same. Please track on it.
Thanks

**Comment by smarek** [comment]
I don't think so @masensio , reported 930 is on older version and our logcat outputs look nothing alike.
May be two issues realted to same topic, Thank you

**Comment by masensio** [comment]
Ok, in this case, I'll reopened it. 
It is possible that the solution for this and #900 will be in the same way.

**Comment by masensio** [comment]
Hi @smarek,

Could you check if you have this problem with the new version (1.7.1)? I've uploaded more than 5 images from Photos app to ownCloud without a problem.

If the bug persists, please describe it with the template https://github.com/owncloud/android/blob/master/issue_template.md. 
In other case, please close the issue or say to us to close it.

Thanks.

**Comment by smarek** [comment]
In 1.7.1 it looks fixed, both ways fixed (from owncloud selecting what to upload, from photos share files to owncloud), closing then. Thanks

**Comment by masensio** [comment]
Thanks for your answer and for closing the issue.
